# Amira Project 601
# Amira
# Generated by Amira 6.0.1
remove -all
remove "grayScale.am" "physics.icol" "s13-old-way.am" "s13-improved.am" "Spatial Graph View" "Spatial Graph View 2"

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 5
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show

if {[_units isUnitsManagementActivated] == 1} {
	_units setDisplayCoordinatesUnit m
	_units setWorkingCoordinatesUnit m
}

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/grayScale.am ] setLabel "grayScale.am"
"grayScale.am" setIconPosition 0 0
"grayScale.am" setNoRemoveAll 1
"grayScale.am" setVar "CustomHelp" {HxColormap256}
"grayScale.am" master disconnect
"grayScale.am" Datafield disconnect
"grayScale.am" fire
"grayScale.am" setMinMax 0 255
"grayScale.am" flags setValue 1
"grayScale.am" shift setMinMax -1 1
"grayScale.am" shift setButtons 0
"grayScale.am" shift setEditButton 1
"grayScale.am" shift setIncrement 0.133333
"grayScale.am" shift setValue 0
"grayScale.am" shift setSubMinMax -1 1
"grayScale.am" scale setMinMax 0 1
"grayScale.am" scale setButtons 0
"grayScale.am" scale setEditButton 1
"grayScale.am" scale setIncrement 0.1
"grayScale.am" scale setValue 1
"grayScale.am" scale setSubMinMax 0 1
"grayScale.am" fire
"grayScale.am" setViewerMask 16383

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/physics.icol ] setLabel "physics.icol"
"physics.icol" setIconPosition 0 0
"physics.icol" setNoRemoveAll 1
"physics.icol" master disconnect
"physics.icol" Datafield disconnect
"physics.icol" fire
"physics.icol" setMinMax 0 1
"physics.icol" flags setValue 1
"physics.icol" shift setMinMax -1 1
"physics.icol" shift setButtons 0
"physics.icol" shift setEditButton 1
"physics.icol" shift setIncrement 0.133333
"physics.icol" shift setValue 0
"physics.icol" shift setSubMinMax -1 1
"physics.icol" scale setMinMax 0 1
"physics.icol" scale setButtons 0
"physics.icol" scale setEditButton 1
"physics.icol" scale setIncrement 0.1
"physics.icol" scale setValue 1
"physics.icol" scale setSubMinMax 0 1
"physics.icol" fire
"physics.icol" setViewerMask 16383

set hideNewModules 0
[ load -unit m ${SCRIPTDIR}/output/am/s13-old-way.am ] setLabel "s13-old-way.am"
"s13-old-way.am" setIconPosition 20 10
"s13-old-way.am" master disconnect
"s13-old-way.am" fire
"s13-old-way.am" fire
"s13-old-way.am" setViewerMask 65535

set hideNewModules 0
[ load -unit m ${SCRIPTDIR}/output/am/s13-improved.am ] setLabel "s13-improved.am"
"s13-improved.am" setIconPosition 20 46
"s13-improved.am" master disconnect
"s13-improved.am" fire
"s13-improved.am" fire
"s13-improved.am" setViewerMask 16383

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View"
"Spatial Graph View" setIconPosition 272 10
"Spatial Graph View" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View" data connect "s13-old-way.am"
"Spatial Graph View" Statistics disconnect
"Spatial Graph View" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View" nodeColormap setLocalRange 1
"Spatial Graph View" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" nodeColormap enableAlpha 1
"Spatial Graph View" nodeColormap enableAlphaToggle 1
"Spatial Graph View" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View" nodeColormap setColorbarMinMax 0 1
"Spatial Graph View" nodeColormap connect "physics.icol"
"Spatial Graph View" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View" segmentColormap setLocalRange 1
"Spatial Graph View" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" segmentColormap enableAlpha 1
"Spatial Graph View" segmentColormap enableAlphaToggle 1
"Spatial Graph View" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View" segmentColormap setColorbarMinMax 0 1
"Spatial Graph View" segmentColormap connect "physics.icol"
"Spatial Graph View" fire
"Spatial Graph View" itemsToShow setValue 0 0
"Spatial Graph View" itemsToShow setToggleVisible 0 1
"Spatial Graph View" itemsToShow setValue 1 1
"Spatial Graph View" itemsToShow setToggleVisible 1 1
"Spatial Graph View" nodeScale setIndex 0 0
"Spatial Graph View" nodeScaleFactor setMinMax 0 50.6644020080566
"Spatial Graph View" nodeScaleFactor setButtons 0
"Spatial Graph View" nodeScaleFactor setEditButton 1
"Spatial Graph View" nodeScaleFactor setIncrement 3.37763
"Spatial Graph View" nodeScaleFactor setValue 2.53322
"Spatial Graph View" nodeScaleFactor setSubMinMax 0 50.6644020080566
"Spatial Graph View" nodeColoring setIndex 0 0
"Spatial Graph View" nodeLabelColoringOptions setValue 0
"Spatial Graph View" nodeColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" segmentStyle setValue 0 1
"Spatial Graph View" segmentStyle setToggleVisible 0 1
"Spatial Graph View" segmentStyle setValue 1 0
"Spatial Graph View" segmentStyle setToggleVisible 1 1
"Spatial Graph View" segmentStyle setValue 2 1
"Spatial Graph View" segmentStyle setToggleVisible 2 1
"Spatial Graph View" tubeScale setIndex 0 3
"Spatial Graph View" tubeScaleFactor setMinMax 0 14.5122213363647
"Spatial Graph View" tubeScaleFactor setButtons 0
"Spatial Graph View" tubeScaleFactor setEditButton 1
"Spatial Graph View" tubeScaleFactor setIncrement 0.967481
"Spatial Graph View" tubeScaleFactor setValue 0.725611
"Spatial Graph View" tubeScaleFactor setSubMinMax 0 14.5122213363647
"Spatial Graph View" segmentWidth setMinMax 0 10
"Spatial Graph View" segmentWidth setButtons 0
"Spatial Graph View" segmentWidth setEditButton 1
"Spatial Graph View" segmentWidth setIncrement 0.666667
"Spatial Graph View" segmentWidth setValue 1
"Spatial Graph View" segmentWidth setSubMinMax 0 10
"Spatial Graph View" segmentColoring setIndex 0 0
"Spatial Graph View" segmentLabelColoringOptions setValue 0
"Spatial Graph View" segmentColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" pointSize setMinMax 0 15
"Spatial Graph View" pointSize setButtons 0
"Spatial Graph View" pointSize setEditButton 1
"Spatial Graph View" pointSize setIncrement 1
"Spatial Graph View" pointSize setValue 4
"Spatial Graph View" pointSize setSubMinMax 0 15
"Spatial Graph View" setVisibility HIJMPLPPBPDLAAAACKPLBHOJ HIJMPLPPBPDLAAAACKPLBHOJ
"Spatial Graph View" fire
"Spatial Graph View" setViewerMask 16383
"Spatial Graph View" setPickable 1

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View 2"
"Spatial Graph View 2" setIconPosition 261 46
"Spatial Graph View 2" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View 2" data connect "s13-improved.am"
"Spatial Graph View 2" Statistics disconnect
"Spatial Graph View 2" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View 2" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View 2" nodeColormap setLocalRange 1
"Spatial Graph View 2" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View 2" nodeColormap enableAlpha 1
"Spatial Graph View 2" nodeColormap enableAlphaToggle 1
"Spatial Graph View 2" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View 2" nodeColormap setColorbarMinMax 0 1
"Spatial Graph View 2" nodeColormap connect "physics.icol"
"Spatial Graph View 2" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View 2" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View 2" segmentColormap setLocalRange 1
"Spatial Graph View 2" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View 2" segmentColormap enableAlpha 1
"Spatial Graph View 2" segmentColormap enableAlphaToggle 1
"Spatial Graph View 2" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View 2" segmentColormap setColorbarMinMax 0 1
"Spatial Graph View 2" segmentColormap connect "physics.icol"
"Spatial Graph View 2" fire
"Spatial Graph View 2" itemsToShow setValue 0 0
"Spatial Graph View 2" itemsToShow setToggleVisible 0 1
"Spatial Graph View 2" itemsToShow setValue 1 1
"Spatial Graph View 2" itemsToShow setToggleVisible 1 1
"Spatial Graph View 2" nodeScale setIndex 0 0
"Spatial Graph View 2" nodeScaleFactor setMinMax 0 50.6644020080566
"Spatial Graph View 2" nodeScaleFactor setButtons 0
"Spatial Graph View 2" nodeScaleFactor setEditButton 1
"Spatial Graph View 2" nodeScaleFactor setIncrement 3.37763
"Spatial Graph View 2" nodeScaleFactor setValue 2.53322
"Spatial Graph View 2" nodeScaleFactor setSubMinMax 0 50.6644020080566
"Spatial Graph View 2" nodeColoring setIndex 0 0
"Spatial Graph View 2" nodeLabelColoringOptions setValue 0
"Spatial Graph View 2" nodeColor setColor 0 0.8 0.8 0.8
"Spatial Graph View 2" segmentStyle setValue 0 1
"Spatial Graph View 2" segmentStyle setToggleVisible 0 1
"Spatial Graph View 2" segmentStyle setValue 1 0
"Spatial Graph View 2" segmentStyle setToggleVisible 1 1
"Spatial Graph View 2" segmentStyle setValue 2 1
"Spatial Graph View 2" segmentStyle setToggleVisible 2 1
"Spatial Graph View 2" tubeScale setIndex 0 3
"Spatial Graph View 2" tubeScaleFactor setMinMax 0 20.1760883331299
"Spatial Graph View 2" tubeScaleFactor setButtons 0
"Spatial Graph View 2" tubeScaleFactor setEditButton 1
"Spatial Graph View 2" tubeScaleFactor setIncrement 1.34507
"Spatial Graph View 2" tubeScaleFactor setValue 1.0088
"Spatial Graph View 2" tubeScaleFactor setSubMinMax 0 20.1760883331299
"Spatial Graph View 2" segmentWidth setMinMax 0 10
"Spatial Graph View 2" segmentWidth setButtons 0
"Spatial Graph View 2" segmentWidth setEditButton 1
"Spatial Graph View 2" segmentWidth setIncrement 0.666667
"Spatial Graph View 2" segmentWidth setValue 1
"Spatial Graph View 2" segmentWidth setSubMinMax 0 10
"Spatial Graph View 2" segmentColoring setIndex 0 0
"Spatial Graph View 2" segmentLabelColoringOptions setValue 0
"Spatial Graph View 2" segmentColor setColor 0 0.8 0.8 0.8
"Spatial Graph View 2" pointSize setMinMax 0 15
"Spatial Graph View 2" pointSize setButtons 0
"Spatial Graph View 2" pointSize setEditButton 1
"Spatial Graph View 2" pointSize setIncrement 1
"Spatial Graph View 2" pointSize setValue 4
"Spatial Graph View 2" pointSize setSubMinMax 0 15
"Spatial Graph View 2" setVisibility HIJMPLPPBPDLAAAACKPLBHOJ HIJMPLPPBPDLAAAACKPLBHOJ
"Spatial Graph View 2" fire
"Spatial Graph View 2" setViewerMask 16383
"Spatial Graph View 2" setPickable 1

set hideNewModules 0

viewer 0 setCameraOrientation 0.990084 0.117897 -0.0763745 1.62383
viewer 0 setCameraPosition 218.719 -1.37265 7.68473
viewer 0 setCameraFocalDistance 255.621
viewer 0 setCameraNearDistance 0.519026
viewer 0 setCameraFarDistance 520.065
viewer 0 setCameraType perspective
viewer 0 setCameraHeightAngle 44.9023
viewer 0 setAutoRedraw 1
viewer 0 redraw

