# Amira Project 601
# Amira
# Generated by Amira 6.0.1
remove -all
remove "grayScale.am" "physics.icol" "s13-r.am" "S13_max_z_projection.tif" "Spatial Graph View" "Animate Ports" "Ortho Slice"

# Create viewers
viewer setVertical 1

viewer 0 setTransparencyType 6
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/grayScale.am ] setLabel "grayScale.am"
"grayScale.am" setIconPosition 0 0
"grayScale.am" setNoRemoveAll 1
"grayScale.am" setVar "CustomHelp" {HxColormap256}
"grayScale.am" master disconnect
"grayScale.am" Datafield disconnect
"grayScale.am" fire
"grayScale.am" setMinMax 0 255
"grayScale.am" flags setValue 1
"grayScale.am" shift setMinMax -1 1
"grayScale.am" shift setButtons 0
"grayScale.am" shift setEditButton 1
"grayScale.am" shift setIncrement 0.133333
"grayScale.am" shift setValue 0
"grayScale.am" shift setSubMinMax -1 1
"grayScale.am" scale setMinMax 0 1
"grayScale.am" scale setButtons 0
"grayScale.am" scale setEditButton 1
"grayScale.am" scale setIncrement 0.1
"grayScale.am" scale setValue 1
"grayScale.am" scale setSubMinMax 0 1
"grayScale.am" fire
"grayScale.am" setViewerMask 16383

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/physics.icol ] setLabel "physics.icol"
"physics.icol" setIconPosition 0 0
"physics.icol" setNoRemoveAll 1
"physics.icol" master disconnect
"physics.icol" Datafield disconnect
"physics.icol" fire
"physics.icol" setMinMax 0 1
"physics.icol" flags setValue 1
"physics.icol" shift setMinMax -1 1
"physics.icol" shift setButtons 0
"physics.icol" shift setEditButton 1
"physics.icol" shift setIncrement 0.133333
"physics.icol" shift setValue 0
"physics.icol" shift setSubMinMax -1 1
"physics.icol" scale setMinMax 0 1
"physics.icol" scale setButtons 0
"physics.icol" scale setEditButton 1
"physics.icol" scale setIncrement 0.1
"physics.icol" scale setValue 1
"physics.icol" scale setSubMinMax 0 1
"physics.icol" fire
"physics.icol" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/../output/am/s13-r.am ] setLabel "s13-r.am"
"s13-r.am" setIconPosition 20 10
"s13-r.am" master disconnect
"s13-r.am" fire
"s13-r.am" fire
"s13-r.am" setViewerMask 16383

set hideNewModules 0
[ load -tif +box 0 611.892 0 571.872 0 1 +mode 100 /home/amir/Projects/radii/old-struct/max_z_projections/S13_max_z_projection.tif ] setLabel "S13_max_z_projection.tif"
"S13_max_z_projection.tif" setIconPosition 20 46
"S13_max_z_projection.tif" master disconnect
"S13_max_z_projection.tif" sharedColormap setDefaultColor 0.8 0.8 0.8
"S13_max_z_projection.tif" sharedColormap setDefaultAlpha 0.500000
"S13_max_z_projection.tif" sharedColormap setLocalRange 1
"S13_max_z_projection.tif" sharedColormap setLocalMinMax 0.000000 1.000000
"S13_max_z_projection.tif" sharedColormap enableAlpha 1
"S13_max_z_projection.tif" sharedColormap enableAlphaToggle 1
"S13_max_z_projection.tif" sharedColormap setAutoAdjustRangeMode 1
"S13_max_z_projection.tif" sharedColormap setColorbarMinMax 0 120
"S13_max_z_projection.tif" sharedColormap disconnect
"S13_max_z_projection.tif" fire
"S13_max_z_projection.tif" fire
"S13_max_z_projection.tif" setViewerMask 16383

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View"
"Spatial Graph View" setIconPosition 336 10
"Spatial Graph View" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View" data connect "s13-r.am"
"Spatial Graph View" Statistics disconnect
"Spatial Graph View" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View" nodeColormap setLocalRange 1
"Spatial Graph View" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" nodeColormap enableAlpha 1
"Spatial Graph View" nodeColormap enableAlphaToggle 1
"Spatial Graph View" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View" nodeColormap setColorbarMinMax 0 1
"Spatial Graph View" nodeColormap connect "physics.icol"
"Spatial Graph View" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View" segmentColormap setLocalRange 1
"Spatial Graph View" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" segmentColormap enableAlpha 1
"Spatial Graph View" segmentColormap enableAlphaToggle 1
"Spatial Graph View" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View" segmentColormap setColorbarMinMax 0 1
"Spatial Graph View" segmentColormap connect "physics.icol"
"Spatial Graph View" fire
"Spatial Graph View" itemsToShow setValue 0 0
"Spatial Graph View" itemsToShow setToggleVisible 0 1
"Spatial Graph View" itemsToShow setValue 1 1
"Spatial Graph View" itemsToShow setToggleVisible 1 1
"Spatial Graph View" nodeScale setIndex 0 0
"Spatial Graph View" nodeScaleFactor setMinMax 0 50.6644020080566
"Spatial Graph View" nodeScaleFactor setButtons 0
"Spatial Graph View" nodeScaleFactor setEditButton 1
"Spatial Graph View" nodeScaleFactor setIncrement 3.37763
"Spatial Graph View" nodeScaleFactor setValue 2.53322
"Spatial Graph View" nodeScaleFactor setSubMinMax 0 50.6644020080566
"Spatial Graph View" nodeColoring setIndex 0 0
"Spatial Graph View" nodeLabelColoringOptions setValue 0
"Spatial Graph View" nodeColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" segmentStyle setValue 0 0
"Spatial Graph View" segmentStyle setToggleVisible 0 1
"Spatial Graph View" segmentStyle setValue 1 0
"Spatial Graph View" segmentStyle setToggleVisible 1 1
"Spatial Graph View" segmentStyle setValue 2 1
"Spatial Graph View" segmentStyle setToggleVisible 2 1
"Spatial Graph View" tubeScale setIndex 0 3
"Spatial Graph View" tubeScaleFactor setMinMax 0 14.5122213363647
"Spatial Graph View" tubeScaleFactor setButtons 0
"Spatial Graph View" tubeScaleFactor setEditButton 1
"Spatial Graph View" tubeScaleFactor setIncrement 0.967481
"Spatial Graph View" tubeScaleFactor setValue 1
"Spatial Graph View" tubeScaleFactor setSubMinMax 0 14.5122213363647
"Spatial Graph View" segmentWidth setMinMax 0 10
"Spatial Graph View" segmentWidth setButtons 0
"Spatial Graph View" segmentWidth setEditButton 1
"Spatial Graph View" segmentWidth setIncrement 0.666667
"Spatial Graph View" segmentWidth setValue 1
"Spatial Graph View" segmentWidth setSubMinMax 0 10
"Spatial Graph View" segmentColoring setIndex 0 0
"Spatial Graph View" segmentLabelColoringOptions setValue 0
"Spatial Graph View" segmentColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" pointSize setMinMax 0 15
"Spatial Graph View" pointSize setButtons 0
"Spatial Graph View" pointSize setEditButton 1
"Spatial Graph View" pointSize setIncrement 1
"Spatial Graph View" pointSize setValue 4
"Spatial Graph View" pointSize setSubMinMax 0 15
"Spatial Graph View" setVisibility HIJMPLPPBPDLAAAACKPLBHOJ HIJMPLPPBPDLAAAACKPLBHOJ
"Spatial Graph View" fire
"Spatial Graph View" setViewerMask 16383
"Spatial Graph View" select
"Spatial Graph View" setPickable 1

set hideNewModules 0
create HxDynamicParameter "Animate Ports"
"Animate Ports" setIconPosition 366 46
"Animate Ports" setVar "CustomHelp" {HxDynamicParameter}
"Animate Ports" object connect "Spatial Graph View"
"Animate Ports" time disconnect
"Animate Ports" time setMinMax 0 100
"Animate Ports" time setSubMinMax 0 100
"Animate Ports" time setValue 5
"Animate Ports" time setDiscrete 0
"Animate Ports" time setIncrement 1
"Animate Ports" time animationMode -once
"Animate Ports" fire
"Animate Ports" port setIndex 0 0
"Animate Ports" fire
"Animate Ports" value setState {(t - 0) * 0.145122 + 0}
"Animate Ports" time setValue 5
"Animate Ports" fire
"Animate Ports" setViewerMask 16383
"Animate Ports" setPickable 1

set hideNewModules 0
create HxOrthoSlice "Ortho Slice"
"Ortho Slice" setIconPosition 384 82
"Ortho Slice" setVar "CustomHelp" {HxOrthoSlice}
"Ortho Slice" data connect "S13_max_z_projection.tif"
"Ortho Slice" fire
"Ortho Slice" sliceOrientation setValue 0
"Ortho Slice" fire
"Ortho Slice" origin  setBoundingBox -1e+08 1e+08 -1e+08 1e+08 -1e+08 1e+08
"Ortho Slice" origin  setImmediate 0
"Ortho Slice" origin  setOrtho 0
"Ortho Slice" origin  showDragger 0
"Ortho Slice" origin  showPoints 0
"Ortho Slice" origin  setPointScale 1
"Ortho Slice" origin  showOptionButton 101
"Ortho Slice" origin  setNumPoints 1 1 1
"Ortho Slice" origin  setCoord 0 305.946 285.936 0.5
"Ortho Slice" normal  setBoundingBox -1e+08 1e+08 -1e+08 1e+08 -1e+08 1e+08
"Ortho Slice" normal  setImmediate 0
"Ortho Slice" normal  setOrtho 0
"Ortho Slice" normal  showDragger 0
"Ortho Slice" normal  showPoints 0
"Ortho Slice" normal  setPointScale 1
"Ortho Slice" normal  showOptionButton 101
"Ortho Slice" normal  setNumPoints 1 1 1
"Ortho Slice" normal  setCoord 0 0 0 1
"Ortho Slice" options setValue 0 0
"Ortho Slice" options setToggleVisible 0 1
"Ortho Slice" options setValue 1 0
"Ortho Slice" options setToggleVisible 1 1
"Ortho Slice" options setValue 2 0
"Ortho Slice" options setToggleVisible 2 1
"Ortho Slice" options setValue 3 0
"Ortho Slice" options setToggleVisible 3 1
"Ortho Slice" mappingType setIndex 0 0
"Ortho Slice" contrastLimit setMinMax 0 -16777216 16777216
"Ortho Slice" contrastLimit setValue 0 7
"Ortho Slice" colormap setDefaultColor 1 0.8 0.5
"Ortho Slice" colormap setDefaultAlpha 1.000000
"Ortho Slice" colormap setLocalRange 1
"Ortho Slice" colormap setLocalMinMax 0.000000 181.000000
"Ortho Slice" colormap enableAlpha 1
"Ortho Slice" colormap enableAlphaToggle 1
"Ortho Slice" colormap setAutoAdjustRangeMode 1
"Ortho Slice" colormap setColorbarMinMax 0 181
"Ortho Slice" colormap connect "grayScale.am"
"Ortho Slice" sliceNumber setMinMax 0 0
"Ortho Slice" sliceNumber setButtons 1
"Ortho Slice" sliceNumber setEditButton 1
"Ortho Slice" sliceNumber setIncrement 1
"Ortho Slice" sliceNumber setValue 0
"Ortho Slice" sliceNumber setSubMinMax 0 0
"Ortho Slice" transparency setValue 0
"Ortho Slice" alpha setMinMax 0 -16777216 16777216
"Ortho Slice" alpha setValue 0 0
"Ortho Slice" alpha setMinMax 1 -16777216 16777216
"Ortho Slice" alpha setValue 1 255
"Ortho Slice" frameSettings setState {item 0 1 item 2 1 color 3 1 0.5 0 }
"Ortho Slice" fire

"Ortho Slice" fire
"Ortho Slice" setViewerMask 16383
"Ortho Slice" setShadowStyle 0
"Ortho Slice" setPickable 1

set hideNewModules 0

viewer 0 setCameraOrientation 0.0777797 0.121732 -0.989511 3.13451
viewer 0 setCameraPosition 183.389 28.3909 374.627
viewer 0 setCameraFocalDistance 420.424
viewer 0 setCameraNearDistance 281.413
viewer 0 setCameraFarDistance 486.188
viewer 0 setCameraType orthographic
viewer 0 setCameraHeight 356.193
viewer 0 setAutoRedraw 1
viewer 0 redraw

s13-r.am show hit
s13-r.am fire
theObjectPool setSelectionOrder {Spatial Graph View}
