#!/abast/anaconda3_isf/bin/python

# -*- coding: utf-8 -*-

import six
import distributed
import matplotlib
matplotlib.use('agg')

if six.PY2:
    client = distributed.Client('localhost:28786')
else:
    client = distributed.Client('localhost:38786')
distributed.client_object_duck_typed = client


def fun():
    import matplotlib
    matplotlib.use('agg')
    import matplotlib.pyplot as plt
    plt.switch_backend('agg')


import re
import sys

from py.test import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
