# Amira Project 601
# Amira
# Generated by Amira 6.0.1
remove -all
remove "temperature.icol" "physics.icol" "500_GP_WR639_cell_1547_SP5C_checked_RE.hoc" "final_spatial_graph_with_radius.am" "Spatial Graph View" "Spatial Graph View 2" "Global Axes"

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 5
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show

if {[_units isUnitsManagementActivated] == 1} {
	_units setDisplayCoordinatesUnit m
	_units setWorkingCoordinatesUnit m
}

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/temperature.icol ] setLabel "temperature.icol"
"temperature.icol" setIconPosition 0 0
"temperature.icol" setNoRemoveAll 1
"temperature.icol" master disconnect
"temperature.icol" Datafield disconnect
"temperature.icol" fire
"temperature.icol" setMinMax 38 44
"temperature.icol" flags setValue 1
"temperature.icol" shift setMinMax -1 1
"temperature.icol" shift setButtons 0
"temperature.icol" shift setEditButton 1
"temperature.icol" shift setIncrement 0.133333
"temperature.icol" shift setValue 0
"temperature.icol" shift setSubMinMax -1 1
"temperature.icol" scale setMinMax 0 1
"temperature.icol" scale setButtons 0
"temperature.icol" scale setEditButton 1
"temperature.icol" scale setIncrement 0.1
"temperature.icol" scale setValue 1
"temperature.icol" scale setSubMinMax 0 1
"temperature.icol" fire
"temperature.icol" setViewerMask 16383

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/physics.icol ] setLabel "physics.icol"
"physics.icol" setIconPosition 0 0
"physics.icol" setNoRemoveAll 1
"physics.icol" master disconnect
"physics.icol" Datafield disconnect
"physics.icol" fire
"physics.icol" setMinMax 0 1
"physics.icol" flags setValue 1
"physics.icol" shift setMinMax -1 1
"physics.icol" shift setButtons 0
"physics.icol" shift setEditButton 1
"physics.icol" shift setIncrement 0.133333
"physics.icol" shift setValue 0
"physics.icol" shift setSubMinMax -1 1
"physics.icol" scale setMinMax 0 1
"physics.icol" scale setButtons 0
"physics.icol" scale setEditButton 1
"physics.icol" scale setIncrement 0.1
"physics.icol" scale setValue 1
"physics.icol" scale setSubMinMax 0 1
"physics.icol" fire
"physics.icol" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/../old-struct/500_GP_WR639_cell_1547_SP5C_checked_RE.hoc ] setLabel "500_GP_WR639_cell_1547_SP5C_checked_RE.hoc"
"500_GP_WR639_cell_1547_SP5C_checked_RE.hoc" setIconPosition 20 31
"500_GP_WR639_cell_1547_SP5C_checked_RE.hoc" master disconnect
"500_GP_WR639_cell_1547_SP5C_checked_RE.hoc" fire
"500_GP_WR639_cell_1547_SP5C_checked_RE.hoc" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"500_GP_WR639_cell_1547_SP5C_checked_RE.hoc" fire
"500_GP_WR639_cell_1547_SP5C_checked_RE.hoc" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/../old-struct/final_spatial_graph_with_radius.am ] setLabel "final_spatial_graph_with_radius.am"
"final_spatial_graph_with_radius.am" setIconPosition 20 67
"final_spatial_graph_with_radius.am" master disconnect
"final_spatial_graph_with_radius.am" fire
"final_spatial_graph_with_radius.am" setTransform -0.109617 1.23256 -0.0360087 0 1.23257 0.110568 0.0325154 0 0.0355901 -0.0329733 -1.237 0 -6512.5 -6116.97 -29.5392 1
"final_spatial_graph_with_radius.am" fire
"final_spatial_graph_with_radius.am" setViewerMask 16383
"final_spatial_graph_with_radius.am" select

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View"
"Spatial Graph View" setIconPosition 299 67
"Spatial Graph View" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View" data connect "500_GP_WR639_cell_1547_SP5C_checked_RE.hoc"
"Spatial Graph View" Statistics disconnect
"Spatial Graph View" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View" nodeColormap setLocalRange 1
"Spatial Graph View" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" nodeColormap enableAlpha 1
"Spatial Graph View" nodeColormap enableAlphaToggle 1
"Spatial Graph View" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View" nodeColormap connect "physics.icol"
"Spatial Graph View" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View" segmentColormap setLocalRange 1
"Spatial Graph View" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" segmentColormap enableAlpha 1
"Spatial Graph View" segmentColormap enableAlphaToggle 1
"Spatial Graph View" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View" segmentColormap connect "physics.icol"
"Spatial Graph View" fire
"Spatial Graph View" itemsToShow setValue 0 0
"Spatial Graph View" itemsToShow setToggleVisible 0 1
"Spatial Graph View" itemsToShow setValue 1 1
"Spatial Graph View" itemsToShow setToggleVisible 1 1
"Spatial Graph View" nodeScale setIndex 0 0
"Spatial Graph View" nodeScaleFactor setMinMax 0 1301.64697265625
"Spatial Graph View" nodeScaleFactor setButtons 0
"Spatial Graph View" nodeScaleFactor setEditButton 1
"Spatial Graph View" nodeScaleFactor setIncrement 86.7765
"Spatial Graph View" nodeScaleFactor setValue 65.0823
"Spatial Graph View" nodeScaleFactor setSubMinMax 0 1301.64697265625
"Spatial Graph View" nodeColoring setIndex 0 0
"Spatial Graph View" nodeLabelColoringOptions setValue 0
"Spatial Graph View" nodeColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" segmentStyle setValue 0 1
"Spatial Graph View" segmentStyle setToggleVisible 0 1
"Spatial Graph View" segmentStyle setValue 1 0
"Spatial Graph View" segmentStyle setToggleVisible 1 1
"Spatial Graph View" segmentStyle setValue 2 0
"Spatial Graph View" segmentStyle setToggleVisible 2 1
"Spatial Graph View" tubeScale setIndex 0 0
"Spatial Graph View" tubeScaleFactor setMinMax 0 1301.64697265625
"Spatial Graph View" tubeScaleFactor setButtons 0
"Spatial Graph View" tubeScaleFactor setEditButton 1
"Spatial Graph View" tubeScaleFactor setIncrement 86.7765
"Spatial Graph View" tubeScaleFactor setValue 65.0823
"Spatial Graph View" tubeScaleFactor setSubMinMax 0 1301.64697265625
"Spatial Graph View" segmentWidth setMinMax 0 10
"Spatial Graph View" segmentWidth setButtons 0
"Spatial Graph View" segmentWidth setEditButton 1
"Spatial Graph View" segmentWidth setIncrement 0.666667
"Spatial Graph View" segmentWidth setValue 1
"Spatial Graph View" segmentWidth setSubMinMax 0 10
"Spatial Graph View" segmentColoring setIndex 0 0
"Spatial Graph View" segmentLabelColoringOptions setValue 0
"Spatial Graph View" segmentColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" pointSize setMinMax 0 15
"Spatial Graph View" pointSize setButtons 0
"Spatial Graph View" pointSize setEditButton 1
"Spatial Graph View" pointSize setIncrement 1
"Spatial Graph View" pointSize setValue 4
"Spatial Graph View" pointSize setSubMinMax 0 15
"Spatial Graph View" setVisibility HIJMPLPPJPHEAAAAFNBNDDMN HIJMPLPPJPHEAAAAFNBNDDMN
"Spatial Graph View" fire
"Spatial Graph View" setViewerMask 16383
"Spatial Graph View" setPickable 1

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View 2"
"Spatial Graph View 2" setIconPosition 288 103
"Spatial Graph View 2" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View 2" data connect "final_spatial_graph_with_radius.am"
"Spatial Graph View 2" Statistics disconnect
"Spatial Graph View 2" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View 2" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View 2" nodeColormap setLocalRange 1
"Spatial Graph View 2" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View 2" nodeColormap enableAlpha 1
"Spatial Graph View 2" nodeColormap enableAlphaToggle 1
"Spatial Graph View 2" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View 2" nodeColormap setColorbarMinMax 0 1
"Spatial Graph View 2" nodeColormap connect "physics.icol"
"Spatial Graph View 2" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View 2" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View 2" segmentColormap setLocalRange 1
"Spatial Graph View 2" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View 2" segmentColormap enableAlpha 1
"Spatial Graph View 2" segmentColormap enableAlphaToggle 1
"Spatial Graph View 2" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View 2" segmentColormap setColorbarMinMax 0 1
"Spatial Graph View 2" segmentColormap connect "physics.icol"
"Spatial Graph View 2" fire
"Spatial Graph View 2" itemsToShow setValue 0 1
"Spatial Graph View 2" itemsToShow setToggleVisible 0 1
"Spatial Graph View 2" itemsToShow setValue 1 1
"Spatial Graph View 2" itemsToShow setToggleVisible 1 1
"Spatial Graph View 2" nodeScale setIndex 0 0
"Spatial Graph View 2" nodeScaleFactor setMinMax 0 103.952613830566
"Spatial Graph View 2" nodeScaleFactor setButtons 0
"Spatial Graph View 2" nodeScaleFactor setEditButton 1
"Spatial Graph View 2" nodeScaleFactor setIncrement 6.93017
"Spatial Graph View 2" nodeScaleFactor setValue 0
"Spatial Graph View 2" nodeScaleFactor setSubMinMax 0 103.952613830566
"Spatial Graph View 2" nodeColoring setIndex 0 0
"Spatial Graph View 2" nodeLabelColoringOptions setValue 0
"Spatial Graph View 2" nodeColor setColor 0 0.8 0.214493 0.214493
"Spatial Graph View 2" segmentStyle setValue 0 1
"Spatial Graph View 2" segmentStyle setToggleVisible 0 1
"Spatial Graph View 2" segmentStyle setValue 1 0
"Spatial Graph View 2" segmentStyle setToggleVisible 1 1
"Spatial Graph View 2" segmentStyle setValue 2 0
"Spatial Graph View 2" segmentStyle setToggleVisible 2 1
"Spatial Graph View 2" tubeScale setIndex 0 0
"Spatial Graph View 2" tubeScaleFactor setMinMax 0 103.952613830566
"Spatial Graph View 2" tubeScaleFactor setButtons 0
"Spatial Graph View 2" tubeScaleFactor setEditButton 1
"Spatial Graph View 2" tubeScaleFactor setIncrement 6.93017
"Spatial Graph View 2" tubeScaleFactor setValue 5.19763
"Spatial Graph View 2" tubeScaleFactor setSubMinMax 0 103.952613830566
"Spatial Graph View 2" segmentWidth setMinMax 0 10
"Spatial Graph View 2" segmentWidth setButtons 0
"Spatial Graph View 2" segmentWidth setEditButton 1
"Spatial Graph View 2" segmentWidth setIncrement 0.666667
"Spatial Graph View 2" segmentWidth setValue 1
"Spatial Graph View 2" segmentWidth setSubMinMax 0 10
"Spatial Graph View 2" segmentColoring setIndex 0 0
"Spatial Graph View 2" segmentLabelColoringOptions setValue 0
"Spatial Graph View 2" segmentColor setColor 0 0.0637681 0.8 0.479899
"Spatial Graph View 2" pointSize setMinMax 0 15
"Spatial Graph View 2" pointSize setButtons 0
"Spatial Graph View 2" pointSize setEditButton 1
"Spatial Graph View 2" pointSize setIncrement 1
"Spatial Graph View 2" pointSize setValue 4
"Spatial Graph View 2" pointSize setSubMinMax 0 15
"Spatial Graph View 2" setVisibility HIJMPLPPBPDPAAAAAOCOBPOB HIJMPLPPBPDPAAAAAOCOBPOB
"Spatial Graph View 2" fire
"Spatial Graph View 2" setViewerMask 16383
"Spatial Graph View 2" setPickable 1

set hideNewModules 0
create HxAxis "Global Axes"
"Global Axes" setIconPosition 344 139
"Global Axes" setVar "CustomHelp" {HxAxis}
"Global Axes" data disconnect
"Global Axes" fire
"Global Axes" axis setValue 0 1
"Global Axes" axis setToggleVisible 0 1
"Global Axes" axis setValue 1 1
"Global Axes" axis setToggleVisible 1 1
"Global Axes" axis setValue 2 1
"Global Axes" axis setToggleVisible 2 1
"Global Axes" options setValue 0 1
"Global Axes" options setToggleVisible 0 1
"Global Axes" options setValue 1 0
"Global Axes" options setToggleVisible 1 1
"Global Axes" options setValue 2 0
"Global Axes" options setToggleVisible 2 1
"Global Axes" thickness setMinMax 1 15
"Global Axes" thickness setButtons 0
"Global Axes" thickness setEditButton 1
"Global Axes" thickness setIncrement 0.933333
"Global Axes" thickness setValue 5
"Global Axes" thickness setSubMinMax 1 15
"Global Axes" color setColor 0 1 0 0
"Global Axes" color setColor 1 0 1 0
"Global Axes" color setColor 2 0 0 1
"Global Axes" color setColor 3 1 0.8 0.5
"Global Axes" axisNames setState {text 1 x text 3 y text 5 z }
"Global Axes" font setState {name: "Arial Unicode MS" size: 10 buttonText: Select bold: 0 italic: 0 color: 0.8 0.8 0.8}
"Global Axes" fire
"Global Axes" setBoundingBox 0 9343.69 0 9343.69 0 9343.69
"Global Axes" setDelta 0 
"Global Axes" setLocalMode 0 
"Global Axes" setFlip 0 0 
"Global Axes" setFlip 1 0 
"Global Axes" setFlip 2 0 
"Global Axes" fire
"Global Axes" setViewerMask 16383
"Global Axes" setPickable 1

set hideNewModules 0

viewer 0 setCameraOrientation 0.560078 -0.578728 0.592779 3.9201
viewer 0 setCameraPosition 10898.2 -9166.97 -1219.31
viewer 0 setCameraFocalDistance 17360.7
viewer 0 setCameraNearDistance -511.19
viewer 0 setCameraFarDistance 22850.2
viewer 0 setCameraType orthographic
viewer 0 setCameraHeight 2872.63
viewer 0 setAutoRedraw 1
viewer 0 redraw

500_GP_WR639_cell_1547_SP5C_checked_RE.hoc show hit
500_GP_WR639_cell_1547_SP5C_checked_RE.hoc fire
theObjectPool setSelectionOrder final_spatial_graph_with_radius.am
