# Amira Project 601
# Amira
# Generated by Amira 6.0.1
remove -all
remove "grayScale.am" "physics.icol" "algined_slices_only_dendrite.am" "500_GP_WR639_cell_1547_SP5C_checked_RE.hoc" "hocFile.landmarkAscii" "hocFile_reduced.landmarkAscii" "conFile.landmarkAscii" "egAm_landmark.landmarkAscii" "Spatial Graph View" "Spatial Graph View 2" "Landmark View" "Landmark View 2" "Landmark View 3" "Landmark View 4"

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 5
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show

if {[_units isUnitsManagementActivated] == 1} {
	_units setDisplayCoordinatesUnit m
	_units setWorkingCoordinatesUnit m
}

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/grayScale.am ] setLabel "grayScale.am"
"grayScale.am" setIconPosition 0 0
"grayScale.am" setNoRemoveAll 1
"grayScale.am" setVar "CustomHelp" {HxColormap256}
"grayScale.am" master disconnect
"grayScale.am" Datafield disconnect
"grayScale.am" fire
"grayScale.am" setMinMax 0 255
"grayScale.am" flags setValue 1
"grayScale.am" shift setMinMax -1 1
"grayScale.am" shift setButtons 0
"grayScale.am" shift setEditButton 1
"grayScale.am" shift setIncrement 0.133333
"grayScale.am" shift setValue 0
"grayScale.am" shift setSubMinMax -1 1
"grayScale.am" scale setMinMax 0 1
"grayScale.am" scale setButtons 0
"grayScale.am" scale setEditButton 1
"grayScale.am" scale setIncrement 0.1
"grayScale.am" scale setValue 1
"grayScale.am" scale setSubMinMax 0 1
"grayScale.am" fire
"grayScale.am" setViewerMask 16383

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/physics.icol ] setLabel "physics.icol"
"physics.icol" setIconPosition 0 0
"physics.icol" setNoRemoveAll 1
"physics.icol" master disconnect
"physics.icol" Datafield disconnect
"physics.icol" fire
"physics.icol" setMinMax 0 1
"physics.icol" flags setValue 1
"physics.icol" shift setMinMax -1 1
"physics.icol" shift setButtons 0
"physics.icol" shift setEditButton 1
"physics.icol" shift setIncrement 0.133333
"physics.icol" shift setValue 0
"physics.icol" shift setSubMinMax -1 1
"physics.icol" scale setMinMax 0 1
"physics.icol" scale setButtons 0
"physics.icol" scale setEditButton 1
"physics.icol" scale setIncrement 0.1
"physics.icol" scale setValue 1
"physics.icol" scale setSubMinMax 0 1
"physics.icol" fire
"physics.icol" setViewerMask 16383

set hideNewModules 0
[ load -unit m ${SCRIPTDIR}/../am_final/algined_slices_only_dendrite.am ] setLabel "algined_slices_only_dendrite.am"
"algined_slices_only_dendrite.am" setIconPosition 20 10
"algined_slices_only_dendrite.am" master disconnect
"algined_slices_only_dendrite.am" fire
"algined_slices_only_dendrite.am" setTransform 0.995406 -0.0957431 0 0 0.0957431 0.995406 0 0 0 0 1 0 209.038 233.623 -840 1
"algined_slices_only_dendrite.am" fire
"algined_slices_only_dendrite.am" setViewerMask 0

set hideNewModules 0
[ load -unit m ${SCRIPTDIR}/../hoc/500_GP_WR639_cell_1547_SP5C_checked_RE.hoc ] setLabel "500_GP_WR639_cell_1547_SP5C_checked_RE.hoc"
"500_GP_WR639_cell_1547_SP5C_checked_RE.hoc" setIconPosition 20 46
"500_GP_WR639_cell_1547_SP5C_checked_RE.hoc" master disconnect
"500_GP_WR639_cell_1547_SP5C_checked_RE.hoc" fire
"500_GP_WR639_cell_1547_SP5C_checked_RE.hoc" fire
"500_GP_WR639_cell_1547_SP5C_checked_RE.hoc" setViewerMask 0

set hideNewModules 0
[ load -unit m ${SCRIPTDIR}/hocFile.landmarkAscii ] setLabel "hocFile.landmarkAscii"
"hocFile.landmarkAscii" setIconPosition 20 82
"hocFile.landmarkAscii" master disconnect
"hocFile.landmarkAscii" ImageSet1 disconnect
"hocFile.landmarkAscii" fire
"hocFile.landmarkAscii" fire
"hocFile.landmarkAscii" setViewerMask 0

set hideNewModules 0
[ load -unit m ${SCRIPTDIR}/hocFile_reduced.landmarkAscii ] setLabel "hocFile_reduced.landmarkAscii"
"hocFile_reduced.landmarkAscii" setIconPosition 20 118
"hocFile_reduced.landmarkAscii" master disconnect
"hocFile_reduced.landmarkAscii" ImageSet1 disconnect
"hocFile_reduced.landmarkAscii" fire
"hocFile_reduced.landmarkAscii" fire
"hocFile_reduced.landmarkAscii" setViewerMask 0

set hideNewModules 0
[ load -unit m ${SCRIPTDIR}/conFile.landmarkAscii ] setLabel "conFile.landmarkAscii"
"conFile.landmarkAscii" setIconPosition 20 154
"conFile.landmarkAscii" master disconnect
"conFile.landmarkAscii" ImageSet1 disconnect
"conFile.landmarkAscii" fire
"conFile.landmarkAscii" fire
"conFile.landmarkAscii" setViewerMask 0

set hideNewModules 0
[ load -unit m ${SCRIPTDIR}/egAm_landmark.landmarkAscii ] setLabel "egAm_landmark.landmarkAscii"
"egAm_landmark.landmarkAscii" setIconPosition 20 190
"egAm_landmark.landmarkAscii" master disconnect
"egAm_landmark.landmarkAscii" ImageSet1 disconnect
"egAm_landmark.landmarkAscii" fire
"egAm_landmark.landmarkAscii" fire
"egAm_landmark.landmarkAscii" setViewerMask 16383

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View"
"Spatial Graph View" setIconPosition 272 10
"Spatial Graph View" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View" data connect "algined_slices_only_dendrite.am"
"Spatial Graph View" Statistics disconnect
"Spatial Graph View" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View" nodeColormap setLocalRange 1
"Spatial Graph View" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" nodeColormap enableAlpha 1
"Spatial Graph View" nodeColormap enableAlphaToggle 1
"Spatial Graph View" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View" nodeColormap setColorbarMinMax 0 1
"Spatial Graph View" nodeColormap connect "physics.icol"
"Spatial Graph View" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View" segmentColormap setLocalRange 1
"Spatial Graph View" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" segmentColormap enableAlpha 1
"Spatial Graph View" segmentColormap enableAlphaToggle 1
"Spatial Graph View" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View" segmentColormap setColorbarMinMax 0 1
"Spatial Graph View" segmentColormap connect "physics.icol"
"Spatial Graph View" fire
"Spatial Graph View" itemsToShow setValue 0 1
"Spatial Graph View" itemsToShow setToggleVisible 0 1
"Spatial Graph View" itemsToShow setValue 1 1
"Spatial Graph View" itemsToShow setToggleVisible 1 1
"Spatial Graph View" nodeScale setIndex 0 0
"Spatial Graph View" nodeScaleFactor setMinMax 0 103.952507019043
"Spatial Graph View" nodeScaleFactor setButtons 0
"Spatial Graph View" nodeScaleFactor setEditButton 1
"Spatial Graph View" nodeScaleFactor setIncrement 6.93017
"Spatial Graph View" nodeScaleFactor setValue 5.19763
"Spatial Graph View" nodeScaleFactor setSubMinMax 0 103.952507019043
"Spatial Graph View" nodeColoring setIndex 0 0
"Spatial Graph View" nodeLabelColoringOptions setValue 0
"Spatial Graph View" nodeColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" segmentStyle setValue 0 1
"Spatial Graph View" segmentStyle setToggleVisible 0 1
"Spatial Graph View" segmentStyle setValue 1 0
"Spatial Graph View" segmentStyle setToggleVisible 1 1
"Spatial Graph View" segmentStyle setValue 2 0
"Spatial Graph View" segmentStyle setToggleVisible 2 1
"Spatial Graph View" tubeScale setIndex 0 0
"Spatial Graph View" tubeScaleFactor setMinMax 0 103.952507019043
"Spatial Graph View" tubeScaleFactor setButtons 0
"Spatial Graph View" tubeScaleFactor setEditButton 1
"Spatial Graph View" tubeScaleFactor setIncrement 6.93017
"Spatial Graph View" tubeScaleFactor setValue 5.19763
"Spatial Graph View" tubeScaleFactor setSubMinMax 0 103.952507019043
"Spatial Graph View" segmentWidth setMinMax 0 10
"Spatial Graph View" segmentWidth setButtons 0
"Spatial Graph View" segmentWidth setEditButton 1
"Spatial Graph View" segmentWidth setIncrement 0.666667
"Spatial Graph View" segmentWidth setValue 1
"Spatial Graph View" segmentWidth setSubMinMax 0 10
"Spatial Graph View" segmentColoring setIndex 0 0
"Spatial Graph View" segmentLabelColoringOptions setValue 0
"Spatial Graph View" segmentColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" pointSize setMinMax 0 15
"Spatial Graph View" pointSize setButtons 0
"Spatial Graph View" pointSize setEditButton 1
"Spatial Graph View" pointSize setIncrement 1
"Spatial Graph View" pointSize setValue 4
"Spatial Graph View" pointSize setSubMinMax 0 15
"Spatial Graph View" setVisibility HIJMPLPPJPDEAAAAJDNECPNB HIJMPLPPJPDKAAAADKJKEHLJ
"Spatial Graph View" fire
"Spatial Graph View" setViewerMask 16383,0
"Spatial Graph View" setPickable 1

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View 2"
"Spatial Graph View 2" setIconPosition 261 82
"Spatial Graph View 2" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View 2" data connect "500_GP_WR639_cell_1547_SP5C_checked_RE.hoc"
"Spatial Graph View 2" Statistics disconnect
"Spatial Graph View 2" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View 2" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View 2" nodeColormap setLocalRange 1
"Spatial Graph View 2" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View 2" nodeColormap enableAlpha 1
"Spatial Graph View 2" nodeColormap enableAlphaToggle 1
"Spatial Graph View 2" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View 2" nodeColormap setColorbarMinMax 0 1
"Spatial Graph View 2" nodeColormap connect "physics.icol"
"Spatial Graph View 2" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View 2" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View 2" segmentColormap setLocalRange 1
"Spatial Graph View 2" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View 2" segmentColormap enableAlpha 1
"Spatial Graph View 2" segmentColormap enableAlphaToggle 1
"Spatial Graph View 2" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View 2" segmentColormap setColorbarMinMax 0 1
"Spatial Graph View 2" segmentColormap connect "physics.icol"
"Spatial Graph View 2" fire
"Spatial Graph View 2" itemsToShow setValue 0 0
"Spatial Graph View 2" itemsToShow setToggleVisible 0 1
"Spatial Graph View 2" itemsToShow setValue 1 1
"Spatial Graph View 2" itemsToShow setToggleVisible 1 1
"Spatial Graph View 2" nodeScale setIndex 0 0
"Spatial Graph View 2" nodeScaleFactor setMinMax 0 1301.64697265625
"Spatial Graph View 2" nodeScaleFactor setButtons 0
"Spatial Graph View 2" nodeScaleFactor setEditButton 1
"Spatial Graph View 2" nodeScaleFactor setIncrement 86.7765
"Spatial Graph View 2" nodeScaleFactor setValue 65.0823
"Spatial Graph View 2" nodeScaleFactor setSubMinMax 0 1301.64697265625
"Spatial Graph View 2" nodeColoring setIndex 0 0
"Spatial Graph View 2" nodeLabelColoringOptions setValue 0
"Spatial Graph View 2" nodeColor setColor 0 0.8 0.8 0.8
"Spatial Graph View 2" segmentStyle setValue 0 1
"Spatial Graph View 2" segmentStyle setToggleVisible 0 1
"Spatial Graph View 2" segmentStyle setValue 1 0
"Spatial Graph View 2" segmentStyle setToggleVisible 1 1
"Spatial Graph View 2" segmentStyle setValue 2 0
"Spatial Graph View 2" segmentStyle setToggleVisible 2 1
"Spatial Graph View 2" tubeScale setIndex 0 0
"Spatial Graph View 2" tubeScaleFactor setMinMax 0 1301.64697265625
"Spatial Graph View 2" tubeScaleFactor setButtons 0
"Spatial Graph View 2" tubeScaleFactor setEditButton 1
"Spatial Graph View 2" tubeScaleFactor setIncrement 86.7765
"Spatial Graph View 2" tubeScaleFactor setValue 65.0823
"Spatial Graph View 2" tubeScaleFactor setSubMinMax 0 1301.64697265625
"Spatial Graph View 2" segmentWidth setMinMax 0 10
"Spatial Graph View 2" segmentWidth setButtons 0
"Spatial Graph View 2" segmentWidth setEditButton 1
"Spatial Graph View 2" segmentWidth setIncrement 0.666667
"Spatial Graph View 2" segmentWidth setValue 1
"Spatial Graph View 2" segmentWidth setSubMinMax 0 10
"Spatial Graph View 2" segmentColoring setIndex 0 0
"Spatial Graph View 2" segmentLabelColoringOptions setValue 0
"Spatial Graph View 2" segmentColor setColor 0 0.8 0.8 0.8
"Spatial Graph View 2" pointSize setMinMax 0 15
"Spatial Graph View 2" pointSize setButtons 0
"Spatial Graph View 2" pointSize setEditButton 1
"Spatial Graph View 2" pointSize setIncrement 1
"Spatial Graph View 2" pointSize setValue 4
"Spatial Graph View 2" pointSize setSubMinMax 0 15
"Spatial Graph View 2" setVisibility HIJMPLPPJPHEAAAAFNBNDDMN HIJMPLPPJPHEAAAAFNBNDDMN
"Spatial Graph View 2" fire
"Spatial Graph View 2" setViewerMask 16383,0
"Spatial Graph View 2" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "Landmark View"
"Landmark View" setIconPosition 294 118
"Landmark View" setVar "CustomHelp" {HxDisplayLandmarks}
"Landmark View" setColor 0 0.78 0.57 0.11
"Landmark View" setColor 1 0.4 0.63 0.7
"Landmark View" setColor 2 0.4 0.75 0.11
"Landmark View" data connect "hocFile.landmarkAscii"
"Landmark View" box disconnect
"Landmark View" fire
"Landmark View" chooseSet setIndex 0 0
"Landmark View" display setValue 0 0
"Landmark View" display setToggleVisible 0 1
"Landmark View" drawStyle setValue 0 1
"Landmark View" drawStyle setToggleVisible 0 1
"Landmark View" drawStyle setValue 1 0
"Landmark View" drawStyle setToggleVisible 1 1
"Landmark View" size setMinMax 0 5
"Landmark View" size setButtons 0
"Landmark View" size setEditButton 1
"Landmark View" size setIncrement 0.333333
"Landmark View" size setValue 0
"Landmark View" size setSubMinMax 0 5
"Landmark View" complexity setMinMax 0 1
"Landmark View" complexity setButtons 0
"Landmark View" complexity setEditButton 1
"Landmark View" complexity setIncrement 0.1
"Landmark View" complexity setValue 1
"Landmark View" complexity setSubMinMax 0 1
"Landmark View" setBaseSize 1450.7
"Landmark View" fire
"Landmark View" setViewerMask 16383,0
"Landmark View" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "Landmark View 2"
"Landmark View 2" setIconPosition 283 154
"Landmark View 2" setVar "CustomHelp" {HxDisplayLandmarks}
"Landmark View 2" setColor 0 0.78 0.57 0.11
"Landmark View 2" setColor 1 0.4 0.63 0.7
"Landmark View 2" setColor 2 0.4 0.75 0.11
"Landmark View 2" data connect "hocFile_reduced.landmarkAscii"
"Landmark View 2" box disconnect
"Landmark View 2" fire
"Landmark View 2" chooseSet setIndex 0 0
"Landmark View 2" display setValue 0 0
"Landmark View 2" display setToggleVisible 0 1
"Landmark View 2" drawStyle setValue 0 0
"Landmark View 2" drawStyle setToggleVisible 0 1
"Landmark View 2" drawStyle setValue 1 0
"Landmark View 2" drawStyle setToggleVisible 1 1
"Landmark View 2" size setMinMax 0 5
"Landmark View 2" size setButtons 0
"Landmark View 2" size setEditButton 1
"Landmark View 2" size setIncrement 0.333333
"Landmark View 2" size setValue 1
"Landmark View 2" size setSubMinMax 0 5
"Landmark View 2" complexity setMinMax 0 1
"Landmark View 2" complexity setButtons 0
"Landmark View 2" complexity setEditButton 1
"Landmark View 2" complexity setIncrement 0.1
"Landmark View 2" complexity setValue 0.25
"Landmark View 2" complexity setSubMinMax 0 1
"Landmark View 2" setBaseSize 122.699
"Landmark View 2" fire
"Landmark View 2" setViewerMask 65535,0
"Landmark View 2" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "Landmark View 3"
"Landmark View 3" setIconPosition 283 190
"Landmark View 3" setVar "CustomHelp" {HxDisplayLandmarks}
"Landmark View 3" setColor 0 0.78 0.57 0.11
"Landmark View 3" setColor 1 0.4 0.63 0.7
"Landmark View 3" setColor 2 0.4 0.75 0.11
"Landmark View 3" data connect "conFile.landmarkAscii"
"Landmark View 3" box disconnect
"Landmark View 3" fire
"Landmark View 3" chooseSet setIndex 0 0
"Landmark View 3" display setValue 0 0
"Landmark View 3" display setToggleVisible 0 1
"Landmark View 3" drawStyle setValue 0 0
"Landmark View 3" drawStyle setToggleVisible 0 1
"Landmark View 3" drawStyle setValue 1 0
"Landmark View 3" drawStyle setToggleVisible 1 1
"Landmark View 3" size setMinMax 0 5
"Landmark View 3" size setButtons 0
"Landmark View 3" size setEditButton 1
"Landmark View 3" size setIncrement 0.333333
"Landmark View 3" size setValue 0.382166
"Landmark View 3" size setSubMinMax 0 5
"Landmark View 3" complexity setMinMax 0 1
"Landmark View 3" complexity setButtons 0
"Landmark View 3" complexity setEditButton 1
"Landmark View 3" complexity setIncrement 0.1
"Landmark View 3" complexity setValue 0.25
"Landmark View 3" complexity setSubMinMax 0 1
"Landmark View 3" setBaseSize 750.793
"Landmark View 3" fire
"Landmark View 3" setViewerMask 16383,0
"Landmark View 3" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "Landmark View 4"
"Landmark View 4" setIconPosition 283 226
"Landmark View 4" setVar "CustomHelp" {HxDisplayLandmarks}
"Landmark View 4" setColor 0 0.78 0.57 0.11
"Landmark View 4" setColor 1 0.4 0.63 0.7
"Landmark View 4" setColor 2 0.4 0.75 0.11
"Landmark View 4" data connect "egAm_landmark.landmarkAscii"
"Landmark View 4" box disconnect
"Landmark View 4" fire
"Landmark View 4" chooseSet setIndex 0 0
"Landmark View 4" display setValue 0 0
"Landmark View 4" display setToggleVisible 0 1
"Landmark View 4" drawStyle setValue 0 0
"Landmark View 4" drawStyle setToggleVisible 0 1
"Landmark View 4" drawStyle setValue 1 0
"Landmark View 4" drawStyle setToggleVisible 1 1
"Landmark View 4" size setMinMax 0 5
"Landmark View 4" size setButtons 0
"Landmark View 4" size setEditButton 1
"Landmark View 4" size setIncrement 0.333333
"Landmark View 4" size setValue 1
"Landmark View 4" size setSubMinMax 0 5
"Landmark View 4" complexity setMinMax 0 1
"Landmark View 4" complexity setButtons 0
"Landmark View 4" complexity setEditButton 1
"Landmark View 4" complexity setIncrement 0.1
"Landmark View 4" complexity setValue 0.25
"Landmark View 4" complexity setSubMinMax 0 1
"Landmark View 4" setBaseSize 99.1586
"Landmark View 4" fire
"Landmark View 4" setViewerMask 16383
"Landmark View 4" select
"Landmark View 4" setPickable 1

set hideNewModules 0

viewer 0 setCameraOrientation 1 0 0 1.5708
viewer 0 setCameraPosition 676.089 -1305.37 111.813
viewer 0 setCameraFocalDistance 1538.16
viewer 0 setCameraNearDistance 1240.08
viewer 0 setCameraFarDistance 1836.83
viewer 0 setCameraType perspective
viewer 0 setCameraHeightAngle 44.9023
viewer 0 setAutoRedraw 1
viewer 0 redraw

theObjectPool setSelectionOrder {Landmark View 4}
