#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/abast/in_silico_framework3/lib/python3.8/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/abast/in_silico_framework3/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/nas1/Data_arco/project_src/in_silico_framework/mechanisms/netcon/x86_64/.libs/libnrnmech.so" "$@"
