#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/gpfs/soma_fs/scratch/meulemeester/anaconda_isf3.8_node/lib/python3.8/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/gpfs/soma_fs/scratch/meulemeester/anaconda_isf3.8_node/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/gpfs/soma_fs/scratch/meulemeester/project_src/in_silico_framework/mechanisms/channels_py3/x86_64/.libs/libnrnmech.so" "$@"
