# Amira Project 202020
# AmiraZIBEdition
# Generated by AmiraZIBEdition 2020.38
remove -all
remove "seismic.col" "physics.icol" "A2_surface.am" "B2_surface.am" "C2_surface.am" "convex_surfaces_avg_barrel_field_pia.surf.am" "convex_surfaces_avg_barrel_field_WM.surf.am" "D2_surface.am" "E2_surface.am" "L2.landmarkAscii" "L4py.landmarkAscii" "L4sp.landmarkAscii" "L4ss.landmarkAscii" "L5st.landmarkAscii" "L5tt.landmarkAscii" "L6cc.landmarkAscii" "L34.landmarkAscii" "L6ct.landmarkAscii" "L6ccinv.landmarkAscii" "EXC.landmarkAscii" "morphology.hoc" "morphology_no_soma.hoc" "black" "red" "Surface View" "Surface View 2" "Surface View 3" "Surface View 4" "Surface View 6" "Surface View 7" "Surface View 5" "Spatial Graph View" "L2color" "L4pycolor" "L4spcolor" "L4sscolor" "L5stcolor" "L5ttcolor" "L6ccinvcolor" "L6ctcolor" "L34color" "L6cccolor" "Spatial Graph View 2" "black_L6ct" "dark_grey_L5tt" "yellow_L2" "light_blue_L5st" "dark_blue_L5tt" "orange_L3py" "L6cccolor 2" "L6ccinvcolor 2" "Vertex View" "Spatial Graph View 3" "Spatial Graph View 4"

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 5
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show

_units setUnitsManagementMode 0

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/seismic.col ] setLabel "seismic.col"
"seismic.col" setIconPosition 0 0
"seismic.col" setNoRemoveAll 1
"seismic.col" setVar "CustomHelp" {HxColormap256}
"seismic.col" fire
"seismic.col" setMinMax 0 255
"seismic.col" flags setValue 1
"seismic.col" shift setMinMax -1 1
"seismic.col" shift setButtons 0
"seismic.col" shift setEditButton 1
"seismic.col" shift setIncrement 0.133333
"seismic.col" shift setValue 0
"seismic.col" shift setSubMinMax -1 1
"seismic.col" scale setMinMax 0 1
"seismic.col" scale setButtons 0
"seismic.col" scale setEditButton 1
"seismic.col" scale setIncrement 0.1
"seismic.col" scale setValue 1
"seismic.col" scale setSubMinMax 0 1
"seismic.col" fire
"seismic.col" setViewerMask 8191

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/physics.icol ] setLabel "physics.icol"
"physics.icol" setIconPosition 0 0
"physics.icol" setNoRemoveAll 1
"physics.icol" fire
"physics.icol" setMinMax 0 1
"physics.icol" flags setValue 1
"physics.icol" shift setMinMax -1 1
"physics.icol" shift setButtons 0
"physics.icol" shift setEditButton 1
"physics.icol" shift setIncrement 0.133333
"physics.icol" shift setValue 0
"physics.icol" shift setSubMinMax -1 1
"physics.icol" scale setMinMax 0 1
"physics.icol" scale setButtons 0
"physics.icol" scale setEditButton 1
"physics.icol" scale setIncrement 0.1
"physics.icol" scale setValue 1
"physics.icol" scale setSubMinMax 0 1
"physics.icol" fire
"physics.icol" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/anatomy/A2_surface.am ] setLabel "A2_surface.am"
"A2_surface.am" setIconPosition 20 299
"A2_surface.am" fire
"A2_surface.am" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/anatomy/B2_surface.am ] setLabel "B2_surface.am"
"B2_surface.am" setIconPosition 18 325
"B2_surface.am" fire
"B2_surface.am" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/anatomy/C2_surface.am ] setLabel "C2_surface.am"
"C2_surface.am" setIconPosition 18 351
"C2_surface.am" fire
"C2_surface.am" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/anatomy/convex_surfaces_avg_barrel_field_pia.surf.am ] setLabel "convex_surfaces_avg_barrel_field_pia.surf.am"
"convex_surfaces_avg_barrel_field_pia.surf.am" setIconPosition 20 471
"convex_surfaces_avg_barrel_field_pia.surf.am" fire
"convex_surfaces_avg_barrel_field_pia.surf.am" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/anatomy/convex_surfaces_avg_barrel_field_WM.surf.am ] setLabel "convex_surfaces_avg_barrel_field_WM.surf.am"
"convex_surfaces_avg_barrel_field_WM.surf.am" setIconPosition 20 443
"convex_surfaces_avg_barrel_field_WM.surf.am" fire
"convex_surfaces_avg_barrel_field_WM.surf.am" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/anatomy/D2_surface.am ] setLabel "D2_surface.am"
"D2_surface.am" setIconPosition 18 378
"D2_surface.am" fire
"D2_surface.am" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/anatomy/E2_surface.am ] setLabel "E2_surface.am"
"E2_surface.am" setIconPosition 17 403
"E2_surface.am" fire
"E2_surface.am" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/presynaptic_cells/0.05/L2.landmarkAscii ] setLabel "L2.landmarkAscii"
"L2.landmarkAscii" setIconPosition 47 548
"L2.landmarkAscii" setVar "CustomXML" {L2.landmarkAscii_config.xml}
"L2.landmarkAscii" fire
"L2.landmarkAscii" setViewerMask 8191

set hideNewModules 0
[ load ${SCRIPTDIR}/presynaptic_cells/0.05/L4py.landmarkAscii ] setLabel "L4py.landmarkAscii"
"L4py.landmarkAscii" setIconPosition 36 574
"L4py.landmarkAscii" setVar "CustomXML" {L4py.landmarkAscii_config.xml}
"L4py.landmarkAscii" fire
"L4py.landmarkAscii" setViewerMask 8191

set hideNewModules 0
[ load ${SCRIPTDIR}/presynaptic_cells/0.05/L4sp.landmarkAscii ] setLabel "L4sp.landmarkAscii"
"L4sp.landmarkAscii" setIconPosition 35 601
"L4sp.landmarkAscii" setVar "CustomXML" {L4sp.landmarkAscii_config.xml}
"L4sp.landmarkAscii" fire
"L4sp.landmarkAscii" setViewerMask 8191

set hideNewModules 0
[ load ${SCRIPTDIR}/presynaptic_cells/0.05/L4ss.landmarkAscii ] setLabel "L4ss.landmarkAscii"
"L4ss.landmarkAscii" setIconPosition 41 628
"L4ss.landmarkAscii" setVar "CustomXML" {L4ss.landmarkAscii_config.xml}
"L4ss.landmarkAscii" fire
"L4ss.landmarkAscii" setViewerMask 8191

set hideNewModules 0
[ load ${SCRIPTDIR}/presynaptic_cells/0.05/L5st.landmarkAscii ] setLabel "L5st.landmarkAscii"
"L5st.landmarkAscii" setIconPosition 46 657
"L5st.landmarkAscii" setVar "CustomXML" {L5st.landmarkAscii_config.xml}
"L5st.landmarkAscii" fire
"L5st.landmarkAscii" setViewerMask 8191

set hideNewModules 0
[ load ${SCRIPTDIR}/presynaptic_cells/0.05/L5tt.landmarkAscii ] setLabel "L5tt.landmarkAscii"
"L5tt.landmarkAscii" setIconPosition 60 682
"L5tt.landmarkAscii" setVar "CustomXML" {L5tt.landmarkAscii_config.xml}
"L5tt.landmarkAscii" fire
"L5tt.landmarkAscii" setViewerMask 8191

set hideNewModules 0
[ load ${SCRIPTDIR}/presynaptic_cells/0.05/L6cc.landmarkAscii ] setLabel "L6cc.landmarkAscii"
"L6cc.landmarkAscii" setIconPosition 60 787
"L6cc.landmarkAscii" setVar "CustomXML" {L6cc.landmarkAscii_config.xml}
"L6cc.landmarkAscii" fire
"L6cc.landmarkAscii" setViewerMask 8191

set hideNewModules 0
[ load ${SCRIPTDIR}/presynaptic_cells/0.05/L34.landmarkAscii ] setLabel "L34.landmarkAscii"
"L34.landmarkAscii" setIconPosition 65 759
"L34.landmarkAscii" setVar "CustomXML" {L34.landmarkAscii_config.xml}
"L34.landmarkAscii" fire
"L34.landmarkAscii" setViewerMask 8191

set hideNewModules 0
[ load ${SCRIPTDIR}/presynaptic_cells/0.05/L6ct.landmarkAscii ] setLabel "L6ct.landmarkAscii"
"L6ct.landmarkAscii" setIconPosition 55 733
"L6ct.landmarkAscii" setVar "CustomXML" {L6ct.landmarkAscii_config.xml}
"L6ct.landmarkAscii" fire
"L6ct.landmarkAscii" setViewerMask 8191

set hideNewModules 0
[ load ${SCRIPTDIR}/presynaptic_cells/0.05/L6ccinv.landmarkAscii ] setLabel "L6ccinv.landmarkAscii"
"L6ccinv.landmarkAscii" setIconPosition 37 707
"L6ccinv.landmarkAscii" setVar "CustomXML" {L6ccinv.landmarkAscii_config.xml}
"L6ccinv.landmarkAscii" fire
"L6ccinv.landmarkAscii" setViewerMask 8191

set hideNewModules 0
[ load ${SCRIPTDIR}/all_cells/0.05/EXC.landmarkAscii ] setLabel "EXC.landmarkAscii"
"EXC.landmarkAscii" setIconPosition 17 -1
"EXC.landmarkAscii" setVar "CustomXML" {EXC.landmarkAscii_config.xml}
"EXC.landmarkAscii" fire
"EXC.landmarkAscii" setViewerMask 8191

set hideNewModules 0
[ load ${SCRIPTDIR}/anatomy/morphology.hoc ] setLabel "morphology.hoc"
"morphology.hoc" setIconPosition 20 33
"morphology.hoc" setVar "CustomXML" {morphology.hoc_config.xml}
"morphology.hoc" fire
"morphology.hoc" fire
"morphology.hoc" setViewerMask 8191

set hideNewModules 0
[ load ${SCRIPTDIR}/anatomy/morphology_no_soma.hoc ] setLabel "morphology_no_soma.hoc"
"morphology_no_soma.hoc" setIconPosition 20 67
"morphology_no_soma.hoc" fire
"morphology_no_soma.hoc" fire
"morphology_no_soma.hoc" setViewerMask 8191

set hideNewModules 0
create HxDisplayLandmarks "black"
"black" setIconPosition 403 129
"black" setVar "CustomHelp" {HxDisplayLandmarks}
"black" setColor 0 0 0 0
"black" setColor 1 0.4 0.63 0.7
"black" setColor 2 0.4 0.75 0.11
"black" fire
"black" chooseSet setIndex 0 0
"black" display setValue 0 0
"black" display setToggleVisible 0 1
"black" drawStyle setValue 0 0
"black" drawStyle setToggleVisible 0 1
"black" drawStyle setValue 1 0
"black" drawStyle setToggleVisible 1 1
"black" size setMinMax 0 5
"black" size setButtons 0
"black" size setEditButton 1
"black" size setIncrement 0.333333
"black" size setValue 0.4
"black" size setSubMinMax 0 5
"black" complexity setMinMax 0 1
"black" complexity setButtons 0
"black" complexity setEditButton 1
"black" complexity setIncrement 0.1
"black" complexity setValue 0.25
"black" complexity setSubMinMax 0 1
"black" setBaseSize 321.489
"black" fire
"black" setViewerMask 16382
"black" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "red"
"red" setIconPosition 381 185
"red" setVar "CustomHelp" {HxDisplayLandmarks}
"red" setColor 0 1 0 0
"red" setColor 1 0.4 0.63 0.7
"red" setColor 2 0.4 0.75 0.11
"red" fire
"red" chooseSet setIndex 0 0
"red" display setValue 0 0
"red" display setToggleVisible 0 1
"red" drawStyle setValue 0 0
"red" drawStyle setToggleVisible 0 1
"red" drawStyle setValue 1 0
"red" drawStyle setToggleVisible 1 1
"red" size setMinMax 0 5
"red" size setButtons 0
"red" size setEditButton 1
"red" size setIncrement 0.333333
"red" size setValue 0.7
"red" size setSubMinMax 0 5
"red" complexity setMinMax 0 1
"red" complexity setButtons 0
"red" complexity setEditButton 1
"red" complexity setIncrement 0.1
"red" complexity setValue 0.25
"red" complexity setSubMinMax 0 1
"red" setBaseSize 323.851
"red" fire
"red" setViewerMask 16382
"red" setPickable 1

set hideNewModules 0
create HxDisplaySurface "Surface View"
"Surface View" setIconPosition 176 300
"Surface View" setVar "CustomHelp" {HxDisplaySurface}
"Surface View" data connect "A2_surface.am"
"Surface View" colormap disconnect
"Surface View" colormap setDefaultColor 0 0 0
"Surface View" colormap setDefaultAlpha 0.500000
"Surface View" colormap activateLocalRange 1
"Surface View" colormap setLocalMinMax 0.000000 1.000000
"Surface View" colormap enableAlpha 1
"Surface View" colormap enableAlphaToggle 1
"Surface View" colormap setAutoAdjustRangeMode 1
"Surface View" fire
"Surface View" drawStyle setValue 1
"Surface View" fire
"Surface View" drawStyle setSpecularLighting 1
"Surface View" drawStyle setTexture 1
"Surface View" drawStyle setAlphaMode 3
"Surface View" drawStyle setCullingMode 0
"Surface View" drawStyle setNormalBinding 0
"Surface View" drawStyle setSortingMode 1
"Surface View" drawStyle setLineWidth 1.000000
"Surface View" drawStyle setOutlineColor 0 0 0.2
"Surface View" textureWrap setIndex 0 1
"Surface View" selectionMode setIndex 0 0
"Surface View" patch setMinMax 0 1
"Surface View" patch setButtons 1
"Surface View" patch setEditButton 1
"Surface View" patch setIncrement 1
"Surface View" patch setValue 0
"Surface View" patch setSubMinMax 0 1
"Surface View" boundaryId setIndex 0 -1
"Surface View" materials setIndex 0 1
"Surface View" materials setIndex 1 0
"Surface View" colorMode setIndex 0 5
"Surface View" baseTrans setMinMax 0 1
"Surface View" baseTrans setButtons 0
"Surface View" baseTrans setEditButton 1
"Surface View" baseTrans setIncrement 0.1
"Surface View" baseTrans setValue 0.95
"Surface View" baseTrans setSubMinMax 0 1
"Surface View" VRMode setIndex 0 0
"Surface View" colorFieldMappingType setValue 0
"Surface View" setLighting 1
"Surface View" fire
"Surface View" hideBox 1
"Surface View" selectTriangles zab HIJMPLPPBPDPOAAHGCAAJDOICCON
"Surface View" fire
"Surface View" setViewerMask 16382
"Surface View" setShadowStyle 0
"Surface View" setPickable 1

set hideNewModules 0
create HxDisplaySurface "Surface View 2"
"Surface View 2" setIconPosition 174 326
"Surface View 2" setVar "CustomHelp" {HxDisplaySurface}
"Surface View 2" data connect "B2_surface.am"
"Surface View 2" colormap disconnect
"Surface View 2" colormap setDefaultColor 0 0 0
"Surface View 2" colormap setDefaultAlpha 0.500000
"Surface View 2" colormap activateLocalRange 1
"Surface View 2" colormap setLocalMinMax 0.000000 1.000000
"Surface View 2" colormap enableAlpha 1
"Surface View 2" colormap enableAlphaToggle 1
"Surface View 2" colormap setAutoAdjustRangeMode 1
"Surface View 2" fire
"Surface View 2" drawStyle setValue 1
"Surface View 2" fire
"Surface View 2" drawStyle setSpecularLighting 1
"Surface View 2" drawStyle setTexture 1
"Surface View 2" drawStyle setAlphaMode 3
"Surface View 2" drawStyle setCullingMode 0
"Surface View 2" drawStyle setNormalBinding 0
"Surface View 2" drawStyle setSortingMode 1
"Surface View 2" drawStyle setLineWidth 1.000000
"Surface View 2" drawStyle setOutlineColor 0 0 0.2
"Surface View 2" textureWrap setIndex 0 1
"Surface View 2" selectionMode setIndex 0 0
"Surface View 2" patch setMinMax 0 1
"Surface View 2" patch setButtons 1
"Surface View 2" patch setEditButton 1
"Surface View 2" patch setIncrement 1
"Surface View 2" patch setValue 0
"Surface View 2" patch setSubMinMax 0 1
"Surface View 2" boundaryId setIndex 0 -1
"Surface View 2" materials setIndex 0 1
"Surface View 2" materials setIndex 1 0
"Surface View 2" colorMode setIndex 0 5
"Surface View 2" baseTrans setMinMax 0 1
"Surface View 2" baseTrans setButtons 0
"Surface View 2" baseTrans setEditButton 1
"Surface View 2" baseTrans setIncrement 0.1
"Surface View 2" baseTrans setValue 0.95
"Surface View 2" baseTrans setSubMinMax 0 1
"Surface View 2" VRMode setIndex 0 0
"Surface View 2" colorFieldMappingType setValue 0
"Surface View 2" setLighting 1
"Surface View 2" fire
"Surface View 2" hideBox 1
"Surface View 2" selectTriangles zab HIJMPLPPBPDPOAAHGCAAJDOICCON
"Surface View 2" fire
"Surface View 2" setViewerMask 16382
"Surface View 2" setShadowStyle 0
"Surface View 2" setPickable 1

set hideNewModules 0
create HxDisplaySurface "Surface View 3"
"Surface View 3" setIconPosition 173 352
"Surface View 3" setVar "CustomHelp" {HxDisplaySurface}
"Surface View 3" data connect "C2_surface.am"
"Surface View 3" colormap disconnect
"Surface View 3" colormap setDefaultColor 0 0 0
"Surface View 3" colormap setDefaultAlpha 0.500000
"Surface View 3" colormap activateLocalRange 1
"Surface View 3" colormap setLocalMinMax 0.000000 1.000000
"Surface View 3" colormap enableAlpha 1
"Surface View 3" colormap enableAlphaToggle 1
"Surface View 3" colormap setAutoAdjustRangeMode 1
"Surface View 3" fire
"Surface View 3" drawStyle setValue 1
"Surface View 3" fire
"Surface View 3" drawStyle setSpecularLighting 1
"Surface View 3" drawStyle setTexture 1
"Surface View 3" drawStyle setAlphaMode 3
"Surface View 3" drawStyle setCullingMode 0
"Surface View 3" drawStyle setNormalBinding 0
"Surface View 3" drawStyle setSortingMode 1
"Surface View 3" drawStyle setLineWidth 1.000000
"Surface View 3" drawStyle setOutlineColor 0 0 0.2
"Surface View 3" textureWrap setIndex 0 1
"Surface View 3" selectionMode setIndex 0 0
"Surface View 3" patch setMinMax 0 1
"Surface View 3" patch setButtons 1
"Surface View 3" patch setEditButton 1
"Surface View 3" patch setIncrement 1
"Surface View 3" patch setValue 0
"Surface View 3" patch setSubMinMax 0 1
"Surface View 3" boundaryId setIndex 0 -1
"Surface View 3" materials setIndex 0 1
"Surface View 3" materials setIndex 1 0
"Surface View 3" colorMode setIndex 0 5
"Surface View 3" baseTrans setMinMax 0 1
"Surface View 3" baseTrans setButtons 0
"Surface View 3" baseTrans setEditButton 1
"Surface View 3" baseTrans setIncrement 0.1
"Surface View 3" baseTrans setValue 0.95
"Surface View 3" baseTrans setSubMinMax 0 1
"Surface View 3" VRMode setIndex 0 0
"Surface View 3" colorFieldMappingType setValue 0
"Surface View 3" setLighting 1
"Surface View 3" fire
"Surface View 3" hideBox 1
"Surface View 3" selectTriangles zab HIJMPLPPBPDPOAAHGCAAJDOICCON
"Surface View 3" fire
"Surface View 3" setViewerMask 16382
"Surface View 3" setShadowStyle 0
"Surface View 3" setPickable 1

set hideNewModules 0
create HxDisplaySurface "Surface View 4"
"Surface View 4" setIconPosition 174 376
"Surface View 4" setVar "CustomHelp" {HxDisplaySurface}
"Surface View 4" data connect "D2_surface.am"
"Surface View 4" colormap disconnect
"Surface View 4" colormap setDefaultColor 0 0 0
"Surface View 4" colormap setDefaultAlpha 0.000000
"Surface View 4" colormap activateLocalRange 1
"Surface View 4" colormap setLocalMinMax 0.000000 1.000000
"Surface View 4" colormap enableAlpha 1
"Surface View 4" colormap enableAlphaToggle 1
"Surface View 4" colormap setAutoAdjustRangeMode 1
"Surface View 4" fire
"Surface View 4" drawStyle setValue 1
"Surface View 4" fire
"Surface View 4" drawStyle setSpecularLighting 1
"Surface View 4" drawStyle setTexture 1
"Surface View 4" drawStyle setAlphaMode 3
"Surface View 4" drawStyle setCullingMode 0
"Surface View 4" drawStyle setNormalBinding 0
"Surface View 4" drawStyle setSortingMode 1
"Surface View 4" drawStyle setLineWidth 1.000000
"Surface View 4" drawStyle setOutlineColor 0 0 0.2
"Surface View 4" textureWrap setIndex 0 1
"Surface View 4" selectionMode setIndex 0 0
"Surface View 4" patch setMinMax 0 1
"Surface View 4" patch setButtons 1
"Surface View 4" patch setEditButton 1
"Surface View 4" patch setIncrement 1
"Surface View 4" patch setValue 0
"Surface View 4" patch setSubMinMax 0 1
"Surface View 4" boundaryId setIndex 0 -1
"Surface View 4" materials setIndex 0 1
"Surface View 4" materials setIndex 1 0
"Surface View 4" colorMode setIndex 0 5
"Surface View 4" baseTrans setMinMax 0 1
"Surface View 4" baseTrans setButtons 0
"Surface View 4" baseTrans setEditButton 1
"Surface View 4" baseTrans setIncrement 0.1
"Surface View 4" baseTrans setValue 0.95
"Surface View 4" baseTrans setSubMinMax 0 1
"Surface View 4" VRMode setIndex 0 0
"Surface View 4" colorFieldMappingType setValue 0
"Surface View 4" setLighting 1
"Surface View 4" fire
"Surface View 4" hideBox 1
"Surface View 4" selectTriangles zab HIJMPLPPBPDPOAAHGCAAJDOICCON
"Surface View 4" fire
"Surface View 4" setViewerMask 16382
"Surface View 4" setShadowStyle 0
"Surface View 4" setPickable 1

set hideNewModules 0
create HxDisplaySurface "Surface View 6"
"Surface View 6" setIconPosition 373 444
"Surface View 6" setVar "CustomHelp" {HxDisplaySurface}
"Surface View 6" data connect "convex_surfaces_avg_barrel_field_WM.surf.am"
"Surface View 6" colormap disconnect
"Surface View 6" colormap setDefaultColor 0 0 0
"Surface View 6" colormap setDefaultAlpha 0.500000
"Surface View 6" colormap activateLocalRange 1
"Surface View 6" colormap setLocalMinMax 0.000000 1.000000
"Surface View 6" colormap enableAlpha 1
"Surface View 6" colormap enableAlphaToggle 1
"Surface View 6" colormap setAutoAdjustRangeMode 1
"Surface View 6" fire
"Surface View 6" drawStyle setValue 1
"Surface View 6" fire
"Surface View 6" drawStyle setSpecularLighting 1
"Surface View 6" drawStyle setTexture 1
"Surface View 6" drawStyle setAlphaMode 3
"Surface View 6" drawStyle setCullingMode 0
"Surface View 6" drawStyle setNormalBinding 0
"Surface View 6" drawStyle setSortingMode 1
"Surface View 6" drawStyle setLineWidth 1.000000
"Surface View 6" drawStyle setOutlineColor 0 0 0.2
"Surface View 6" textureWrap setIndex 0 1
"Surface View 6" selectionMode setIndex 0 0
"Surface View 6" patch setMinMax 0 1
"Surface View 6" patch setButtons 1
"Surface View 6" patch setEditButton 1
"Surface View 6" patch setIncrement 1
"Surface View 6" patch setValue 0
"Surface View 6" patch setSubMinMax 0 1
"Surface View 6" boundaryId setIndex 0 -1
"Surface View 6" materials setIndex 0 1
"Surface View 6" materials setIndex 1 0
"Surface View 6" colorMode setIndex 0 5
"Surface View 6" baseTrans setMinMax 0 1
"Surface View 6" baseTrans setButtons 0
"Surface View 6" baseTrans setEditButton 1
"Surface View 6" baseTrans setIncrement 0.1
"Surface View 6" baseTrans setValue 0.95
"Surface View 6" baseTrans setSubMinMax 0 1
"Surface View 6" VRMode setIndex 0 0
"Surface View 6" colorFieldMappingType setValue 0
"Surface View 6" setLighting 1
"Surface View 6" fire
"Surface View 6" hideBox 1
"Surface View 6" selectTriangles zab HIJMPLPPJPHIMAAPMEAAJABECOOB
"Surface View 6" fire
"Surface View 6" setViewerMask 16383
"Surface View 6" setShadowStyle 0
"Surface View 6" setPickable 1

set hideNewModules 0
create HxDisplaySurface "Surface View 7"
"Surface View 7" setIconPosition 373 471
"Surface View 7" setVar "CustomHelp" {HxDisplaySurface}
"Surface View 7" data connect "convex_surfaces_avg_barrel_field_pia.surf.am"
"Surface View 7" colormap disconnect
"Surface View 7" colormap setDefaultColor 0 0 0
"Surface View 7" colormap setDefaultAlpha 0.500000
"Surface View 7" colormap activateLocalRange 1
"Surface View 7" colormap setLocalMinMax 0.000000 1.000000
"Surface View 7" colormap enableAlpha 1
"Surface View 7" colormap enableAlphaToggle 1
"Surface View 7" colormap setAutoAdjustRangeMode 1
"Surface View 7" fire
"Surface View 7" drawStyle setValue 1
"Surface View 7" fire
"Surface View 7" drawStyle setSpecularLighting 1
"Surface View 7" drawStyle setTexture 1
"Surface View 7" drawStyle setAlphaMode 3
"Surface View 7" drawStyle setCullingMode 0
"Surface View 7" drawStyle setNormalBinding 0
"Surface View 7" drawStyle setSortingMode 1
"Surface View 7" drawStyle setLineWidth 1.000000
"Surface View 7" drawStyle setOutlineColor 0 0 0.2
"Surface View 7" textureWrap setIndex 0 1
"Surface View 7" selectionMode setIndex 0 0
"Surface View 7" patch setMinMax 0 1
"Surface View 7" patch setButtons 1
"Surface View 7" patch setEditButton 1
"Surface View 7" patch setIncrement 1
"Surface View 7" patch setValue 0
"Surface View 7" patch setSubMinMax 0 1
"Surface View 7" boundaryId setIndex 0 -1
"Surface View 7" materials setIndex 0 1
"Surface View 7" materials setIndex 1 0
"Surface View 7" colorMode setIndex 0 5
"Surface View 7" baseTrans setMinMax 0 1
"Surface View 7" baseTrans setButtons 0
"Surface View 7" baseTrans setEditButton 1
"Surface View 7" baseTrans setIncrement 0.1
"Surface View 7" baseTrans setValue 0.95
"Surface View 7" baseTrans setSubMinMax 0 1
"Surface View 7" VRMode setIndex 0 0
"Surface View 7" colorFieldMappingType setValue 0
"Surface View 7" setLighting 1
"Surface View 7" fire
"Surface View 7" hideBox 1
"Surface View 7" selectTriangles zab HIJMPLPPJPHIMAAPMEAAJABECOOB
"Surface View 7" fire
"Surface View 7" setViewerMask 16383
"Surface View 7" setShadowStyle 0
"Surface View 7" setPickable 1

set hideNewModules 0
create HxDisplaySurface "Surface View 5"
"Surface View 5" setIconPosition 180 402
"Surface View 5" setVar "CustomHelp" {HxDisplaySurface}
"Surface View 5" data connect "E2_surface.am"
"Surface View 5" colormap disconnect
"Surface View 5" colormap setDefaultColor 0 0 0
"Surface View 5" colormap setDefaultAlpha 0.500000
"Surface View 5" colormap activateLocalRange 1
"Surface View 5" colormap setLocalMinMax 0.000000 1.000000
"Surface View 5" colormap enableAlpha 1
"Surface View 5" colormap enableAlphaToggle 1
"Surface View 5" colormap setAutoAdjustRangeMode 1
"Surface View 5" fire
"Surface View 5" drawStyle setValue 1
"Surface View 5" fire
"Surface View 5" drawStyle setSpecularLighting 1
"Surface View 5" drawStyle setTexture 1
"Surface View 5" drawStyle setAlphaMode 3
"Surface View 5" drawStyle setCullingMode 0
"Surface View 5" drawStyle setNormalBinding 0
"Surface View 5" drawStyle setSortingMode 1
"Surface View 5" drawStyle setLineWidth 1.000000
"Surface View 5" drawStyle setOutlineColor 0 0 0.2
"Surface View 5" textureWrap setIndex 0 1
"Surface View 5" selectionMode setIndex 0 0
"Surface View 5" patch setMinMax 0 1
"Surface View 5" patch setButtons 1
"Surface View 5" patch setEditButton 1
"Surface View 5" patch setIncrement 1
"Surface View 5" patch setValue 0
"Surface View 5" patch setSubMinMax 0 1
"Surface View 5" boundaryId setIndex 0 -1
"Surface View 5" materials setIndex 0 1
"Surface View 5" materials setIndex 1 0
"Surface View 5" colorMode setIndex 0 5
"Surface View 5" baseTrans setMinMax 0 1
"Surface View 5" baseTrans setButtons 0
"Surface View 5" baseTrans setEditButton 1
"Surface View 5" baseTrans setIncrement 0.1
"Surface View 5" baseTrans setValue 0.95
"Surface View 5" baseTrans setSubMinMax 0 1
"Surface View 5" VRMode setIndex 0 0
"Surface View 5" colorFieldMappingType setValue 0
"Surface View 5" setLighting 1
"Surface View 5" fire
"Surface View 5" hideBox 1
"Surface View 5" selectTriangles zab HIJMPLPPBPDPOAAHGCAAJDOICCON
"Surface View 5" fire
"Surface View 5" setViewerMask 16382
"Surface View 5" setShadowStyle 0
"Surface View 5" setPickable 1

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View"
"Spatial Graph View" setIconPosition 299 865
"Spatial Graph View" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View" setVar "CustomXML" {HxSpatialGraphView_config.xml}
"Spatial Graph View" nodeColormap connect "physics.icol"
"Spatial Graph View" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View" nodeColormap activateLocalRange 1
"Spatial Graph View" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" nodeColormap enableAlpha 1
"Spatial Graph View" nodeColormap enableAlphaToggle 1
"Spatial Graph View" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View" segmentColormap connect "physics.icol"
"Spatial Graph View" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View" segmentColormap activateLocalRange 1
"Spatial Graph View" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" segmentColormap enableAlpha 1
"Spatial Graph View" segmentColormap enableAlphaToggle 1
"Spatial Graph View" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View" fire
"Spatial Graph View" nodeOnOff setValue 0
"Spatial Graph View" nodeScale setIndex 0 0
"Spatial Graph View" fire
"Spatial Graph View" nodeScaleFactor setMinMax 0 1
"Spatial Graph View" nodeScaleFactor setButtons 0
"Spatial Graph View" nodeScaleFactor setEditButton 1
"Spatial Graph View" nodeScaleFactor setIncrement 0.0666667
"Spatial Graph View" nodeScaleFactor setValue 0.05
"Spatial Graph View" nodeScaleFactor setSubMinMax 0 1
"Spatial Graph View" nodeColoring setIndex 0 0
"Spatial Graph View" nodeLabelColoringOptions setValue 0
"Spatial Graph View" nodeColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" segmentOnOff setValue 1
"Spatial Graph View" segmentStyle setValue 0 0
"Spatial Graph View" segmentStyle setToggleVisible 0 1
"Spatial Graph View" segmentStyle setValue 1 0
"Spatial Graph View" segmentStyle setToggleVisible 1 1
"Spatial Graph View" segmentStyle setValue 2 1
"Spatial Graph View" segmentStyle setToggleVisible 2 1
"Spatial Graph View" tubeScale setIndex 0 0
"Spatial Graph View" fire
"Spatial Graph View" tubeScaleFactor setMinMax 0 1
"Spatial Graph View" tubeScaleFactor setButtons 0
"Spatial Graph View" tubeScaleFactor setEditButton 1
"Spatial Graph View" tubeScaleFactor setIncrement 0.0666667
"Spatial Graph View" tubeScaleFactor setValue 0.0167034
"Spatial Graph View" tubeScaleFactor setSubMinMax 0 1
"Spatial Graph View" segmentWidth setMinMax 0 10
"Spatial Graph View" segmentWidth setButtons 0
"Spatial Graph View" segmentWidth setEditButton 1
"Spatial Graph View" segmentWidth setIncrement 0.666667
"Spatial Graph View" segmentWidth setValue 1
"Spatial Graph View" segmentWidth setSubMinMax 0 10
"Spatial Graph View" segmentColoring setIndex 0 0
"Spatial Graph View" segmentLabelColoringOptions setValue 0
"Spatial Graph View" segmentColor setColor 0 0 0 1
"Spatial Graph View" pointSize setMinMax 0 15
"Spatial Graph View" pointSize setButtons 0
"Spatial Graph View" pointSize setEditButton 1
"Spatial Graph View" pointSize setIncrement 1
"Spatial Graph View" pointSize setValue 4
"Spatial Graph View" pointSize setSubMinMax 0 15
"Spatial Graph View" fire
"Spatial Graph View" setViewerMask 16383
"Spatial Graph View" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L2color"
"L2color" setIconPosition 204 551
"L2color" setVar "CustomHelp" {HxDisplayLandmarks}
"L2color" setVar "CustomXML" {HxDisplayLandmarks_config.xml}
"L2color" setColor 0 0 0.623529 0.890196
"L2color" setColor 1 0.4 0.63 0.7
"L2color" setColor 2 0.4 0.75 0.11
"L2color" data connect "L2.landmarkAscii"
"L2color" fire
"L2color" chooseSet setIndex 0 0
"L2color" display setValue 0 0
"L2color" display setToggleVisible 0 1
"L2color" drawStyle setValue 0 0
"L2color" drawStyle setToggleVisible 0 1
"L2color" drawStyle setValue 1 0
"L2color" drawStyle setToggleVisible 1 1
"L2color" size setMinMax 0 5
"L2color" size setButtons 0
"L2color" size setEditButton 1
"L2color" size setIncrement 0.333333
"L2color" size setValue 0.4
"L2color" size setSubMinMax 0 5
"L2color" complexity setMinMax 0 1
"L2color" complexity setButtons 0
"L2color" complexity setEditButton 1
"L2color" complexity setIncrement 0.1
"L2color" complexity setValue 0.25
"L2color" complexity setSubMinMax 0 1
"L2color" setBaseSize 321.489
"L2color" fire
"L2color" setViewerMask 16383
"L2color" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L4pycolor"
"L4pycolor" setIconPosition 198 577
"L4pycolor" setVar "CustomHelp" {HxDisplayLandmarks}
"L4pycolor" setColor 0 0.572549 0.866667 0.501961
"L4pycolor" setColor 1 0.4 0.63 0.7
"L4pycolor" setColor 2 0.4 0.75 0.11
"L4pycolor" data connect "L4py.landmarkAscii"
"L4pycolor" fire
"L4pycolor" chooseSet setIndex 0 0
"L4pycolor" display setValue 0 0
"L4pycolor" display setToggleVisible 0 1
"L4pycolor" drawStyle setValue 0 0
"L4pycolor" drawStyle setToggleVisible 0 1
"L4pycolor" drawStyle setValue 1 0
"L4pycolor" drawStyle setToggleVisible 1 1
"L4pycolor" size setMinMax 0 5
"L4pycolor" size setButtons 0
"L4pycolor" size setEditButton 1
"L4pycolor" size setIncrement 0.333333
"L4pycolor" size setValue 0.4
"L4pycolor" size setSubMinMax 0 5
"L4pycolor" complexity setMinMax 0 1
"L4pycolor" complexity setButtons 0
"L4pycolor" complexity setEditButton 1
"L4pycolor" complexity setIncrement 0.1
"L4pycolor" complexity setValue 0.25
"L4pycolor" complexity setSubMinMax 0 1
"L4pycolor" setBaseSize 321.489
"L4pycolor" fire
"L4pycolor" setViewerMask 16383
"L4pycolor" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L4spcolor"
"L4spcolor" setIconPosition 193 605
"L4spcolor" setVar "CustomHelp" {HxDisplayLandmarks}
"L4spcolor" setColor 0 0.396078 0.709804 0.423529
"L4spcolor" setColor 1 0.4 0.63 0.7
"L4spcolor" setColor 2 0.4 0.75 0.11
"L4spcolor" data connect "L4sp.landmarkAscii"
"L4spcolor" fire
"L4spcolor" chooseSet setIndex 0 0
"L4spcolor" display setValue 0 0
"L4spcolor" display setToggleVisible 0 1
"L4spcolor" drawStyle setValue 0 0
"L4spcolor" drawStyle setToggleVisible 0 1
"L4spcolor" drawStyle setValue 1 0
"L4spcolor" drawStyle setToggleVisible 1 1
"L4spcolor" size setMinMax 0 5
"L4spcolor" size setButtons 0
"L4spcolor" size setEditButton 1
"L4spcolor" size setIncrement 0.333333
"L4spcolor" size setValue 0.4
"L4spcolor" size setSubMinMax 0 5
"L4spcolor" complexity setMinMax 0 1
"L4spcolor" complexity setButtons 0
"L4spcolor" complexity setEditButton 1
"L4spcolor" complexity setIncrement 0.1
"L4spcolor" complexity setValue 0.25
"L4spcolor" complexity setSubMinMax 0 1
"L4spcolor" setBaseSize 321.489
"L4spcolor" fire
"L4spcolor" setViewerMask 16383
"L4spcolor" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L4sscolor"
"L4sscolor" setIconPosition 200 629
"L4sscolor" setVar "CustomHelp" {HxDisplayLandmarks}
"L4sscolor" setVar "CustomXML" {HxDisplayLandmarks_config.xml}
"L4sscolor" setColor 0 0.396078 0.709804 0.423529
"L4sscolor" setColor 1 0.4 0.63 0.7
"L4sscolor" setColor 2 0.4 0.75 0.11
"L4sscolor" data connect "L4ss.landmarkAscii"
"L4sscolor" fire
"L4sscolor" chooseSet setIndex 0 0
"L4sscolor" display setValue 0 0
"L4sscolor" display setToggleVisible 0 1
"L4sscolor" drawStyle setValue 0 0
"L4sscolor" drawStyle setToggleVisible 0 1
"L4sscolor" drawStyle setValue 1 0
"L4sscolor" drawStyle setToggleVisible 1 1
"L4sscolor" size setMinMax 0 5
"L4sscolor" size setButtons 0
"L4sscolor" size setEditButton 1
"L4sscolor" size setIncrement 0.333333
"L4sscolor" size setValue 0.4
"L4sscolor" size setSubMinMax 0 5
"L4sscolor" complexity setMinMax 0 1
"L4sscolor" complexity setButtons 0
"L4sscolor" complexity setEditButton 1
"L4sscolor" complexity setIncrement 0.1
"L4sscolor" complexity setValue 0.25
"L4sscolor" complexity setSubMinMax 0 1
"L4sscolor" setBaseSize 321.489
"L4sscolor" fire
"L4sscolor" setViewerMask 16383
"L4sscolor" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L5stcolor"
"L5stcolor" setIconPosition 224 654
"L5stcolor" setVar "CustomHelp" {HxDisplayLandmarks}
"L5stcolor" setColor 0 0.996078 0.929412 0.00392157
"L5stcolor" setColor 1 0.4 0.63 0.7
"L5stcolor" setColor 2 0.4 0.75 0.11
"L5stcolor" data connect "L5st.landmarkAscii"
"L5stcolor" fire
"L5stcolor" chooseSet setIndex 0 0
"L5stcolor" display setValue 0 0
"L5stcolor" display setToggleVisible 0 1
"L5stcolor" drawStyle setValue 0 0
"L5stcolor" drawStyle setToggleVisible 0 1
"L5stcolor" drawStyle setValue 1 0
"L5stcolor" drawStyle setToggleVisible 1 1
"L5stcolor" size setMinMax 0 5
"L5stcolor" size setButtons 0
"L5stcolor" size setEditButton 1
"L5stcolor" size setIncrement 0.333333
"L5stcolor" size setValue 0.4
"L5stcolor" size setSubMinMax 0 5
"L5stcolor" complexity setMinMax 0 1
"L5stcolor" complexity setButtons 0
"L5stcolor" complexity setEditButton 1
"L5stcolor" complexity setIncrement 0.1
"L5stcolor" complexity setValue 0.25
"L5stcolor" complexity setSubMinMax 0 1
"L5stcolor" setBaseSize 321.489
"L5stcolor" fire
"L5stcolor" setViewerMask 16383
"L5stcolor" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L5ttcolor"
"L5ttcolor" setIconPosition 567 678
"L5ttcolor" setVar "CustomHelp" {HxDisplayLandmarks}
"L5ttcolor" setColor 0 0.85098 0.85098 0.85098
"L5ttcolor" setColor 1 0.4 0.63 0.7
"L5ttcolor" setColor 2 0.4 0.75 0.11
"L5ttcolor" fire
"L5ttcolor" chooseSet setIndex 0 0
"L5ttcolor" display setValue 0 0
"L5ttcolor" display setToggleVisible 0 1
"L5ttcolor" drawStyle setValue 0 0
"L5ttcolor" drawStyle setToggleVisible 0 1
"L5ttcolor" drawStyle setValue 1 0
"L5ttcolor" drawStyle setToggleVisible 1 1
"L5ttcolor" size setMinMax 0 5
"L5ttcolor" size setButtons 0
"L5ttcolor" size setEditButton 1
"L5ttcolor" size setIncrement 0.333333
"L5ttcolor" size setValue 0.4
"L5ttcolor" size setSubMinMax 0 5
"L5ttcolor" complexity setMinMax 0 1
"L5ttcolor" complexity setButtons 0
"L5ttcolor" complexity setEditButton 1
"L5ttcolor" complexity setIncrement 0.1
"L5ttcolor" complexity setValue 0.25
"L5ttcolor" complexity setSubMinMax 0 1
"L5ttcolor" setBaseSize 323.851
"L5ttcolor" fire
"L5ttcolor" setViewerMask 16383
"L5ttcolor" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L6ccinvcolor"
"L6ccinvcolor" setIconPosition 229 703
"L6ccinvcolor" setVar "CustomHelp" {HxDisplayLandmarks}
"L6ccinvcolor" setColor 0 0.890196 0.027451 0.0745098
"L6ccinvcolor" setColor 1 0.4 0.63 0.7
"L6ccinvcolor" setColor 2 0.4 0.75 0.11
"L6ccinvcolor" data connect "L6ccinv.landmarkAscii"
"L6ccinvcolor" fire
"L6ccinvcolor" chooseSet setIndex 0 0
"L6ccinvcolor" display setValue 0 0
"L6ccinvcolor" display setToggleVisible 0 1
"L6ccinvcolor" drawStyle setValue 0 0
"L6ccinvcolor" drawStyle setToggleVisible 0 1
"L6ccinvcolor" drawStyle setValue 1 0
"L6ccinvcolor" drawStyle setToggleVisible 1 1
"L6ccinvcolor" size setMinMax 0 5
"L6ccinvcolor" size setButtons 0
"L6ccinvcolor" size setEditButton 1
"L6ccinvcolor" size setIncrement 0.333333
"L6ccinvcolor" size setValue 0.4
"L6ccinvcolor" size setSubMinMax 0 5
"L6ccinvcolor" complexity setMinMax 0 1
"L6ccinvcolor" complexity setButtons 0
"L6ccinvcolor" complexity setEditButton 1
"L6ccinvcolor" complexity setIncrement 0.1
"L6ccinvcolor" complexity setValue 0.25
"L6ccinvcolor" complexity setSubMinMax 0 1
"L6ccinvcolor" setBaseSize 321.489
"L6ccinvcolor" fire
"L6ccinvcolor" setViewerMask 16383
"L6ccinvcolor" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L6ctcolor"
"L6ctcolor" setIconPosition 223 732
"L6ctcolor" setVar "CustomHelp" {HxDisplayLandmarks}
"L6ctcolor" setColor 0 0.55 0 1
"L6ctcolor" setColor 1 0.4 0.63 0.7
"L6ctcolor" setColor 2 0.4 0.75 0.11
"L6ctcolor" data connect "L6ct.landmarkAscii"
"L6ctcolor" fire
"L6ctcolor" chooseSet setIndex 0 0
"L6ctcolor" display setValue 0 0
"L6ctcolor" display setToggleVisible 0 1
"L6ctcolor" drawStyle setValue 0 0
"L6ctcolor" drawStyle setToggleVisible 0 1
"L6ctcolor" drawStyle setValue 1 0
"L6ctcolor" drawStyle setToggleVisible 1 1
"L6ctcolor" size setMinMax 0 5
"L6ctcolor" size setButtons 0
"L6ctcolor" size setEditButton 1
"L6ctcolor" size setIncrement 0.333333
"L6ctcolor" size setValue 0.4
"L6ctcolor" size setSubMinMax 0 5
"L6ctcolor" complexity setMinMax 0 1
"L6ctcolor" complexity setButtons 0
"L6ctcolor" complexity setEditButton 1
"L6ctcolor" complexity setIncrement 0.1
"L6ctcolor" complexity setValue 0.25
"L6ctcolor" complexity setSubMinMax 0 1
"L6ctcolor" setBaseSize 321.489
"L6ctcolor" fire
"L6ctcolor" setViewerMask 16383
"L6ctcolor" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L34color"
"L34color" setIconPosition 227 757
"L34color" setVar "CustomHelp" {HxDisplayLandmarks}
"L34color" setColor 0 0.0470588 0 1
"L34color" setColor 1 0.4 0.63 0.7
"L34color" setColor 2 0.4 0.75 0.11
"L34color" data connect "L34.landmarkAscii"
"L34color" fire
"L34color" chooseSet setIndex 0 0
"L34color" display setValue 0 0
"L34color" display setToggleVisible 0 1
"L34color" drawStyle setValue 0 0
"L34color" drawStyle setToggleVisible 0 1
"L34color" drawStyle setValue 1 0
"L34color" drawStyle setToggleVisible 1 1
"L34color" size setMinMax 0 5
"L34color" size setButtons 0
"L34color" size setEditButton 1
"L34color" size setIncrement 0.333333
"L34color" size setValue 0.4
"L34color" size setSubMinMax 0 5
"L34color" complexity setMinMax 0 1
"L34color" complexity setButtons 0
"L34color" complexity setEditButton 1
"L34color" complexity setIncrement 0.1
"L34color" complexity setValue 0.25
"L34color" complexity setSubMinMax 0 1
"L34color" setBaseSize 321.489
"L34color" fire
"L34color" setViewerMask 16383
"L34color" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L6cccolor"
"L6cccolor" setIconPosition 221 783
"L6cccolor" setVar "CustomHelp" {HxDisplayLandmarks}
"L6cccolor" setVar "CustomXML" {HxDisplayLandmarks_config.xml}
"L6cccolor" setColor 0 0.937255 0.623529 0.619608
"L6cccolor" setColor 1 0.4 0.63 0.7
"L6cccolor" setColor 2 0.4 0.75 0.11
"L6cccolor" data connect "L6cc.landmarkAscii"
"L6cccolor" fire
"L6cccolor" chooseSet setIndex 0 0
"L6cccolor" display setValue 0 0
"L6cccolor" display setToggleVisible 0 1
"L6cccolor" drawStyle setValue 0 0
"L6cccolor" drawStyle setToggleVisible 0 1
"L6cccolor" drawStyle setValue 1 0
"L6cccolor" drawStyle setToggleVisible 1 1
"L6cccolor" size setMinMax 0 5
"L6cccolor" size setButtons 0
"L6cccolor" size setEditButton 1
"L6cccolor" size setIncrement 0.333333
"L6cccolor" size setValue 0.4
"L6cccolor" size setSubMinMax 0 5
"L6cccolor" complexity setMinMax 0 1
"L6cccolor" complexity setButtons 0
"L6cccolor" complexity setEditButton 1
"L6cccolor" complexity setIncrement 0.1
"L6cccolor" complexity setValue 0.25
"L6cccolor" complexity setSubMinMax 0 1
"L6cccolor" setBaseSize 321.489
"L6cccolor" fire
"L6cccolor" setViewerMask 16383
"L6cccolor" setPickable 1

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View 2"
"Spatial Graph View 2" setIconPosition 316 826
"Spatial Graph View 2" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View 2" setVar "CustomXML" {HxSpatialGraphView_config.xml}
"Spatial Graph View 2" nodeColormap connect "physics.icol"
"Spatial Graph View 2" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View 2" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View 2" nodeColormap activateLocalRange 1
"Spatial Graph View 2" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View 2" nodeColormap enableAlpha 1
"Spatial Graph View 2" nodeColormap enableAlphaToggle 1
"Spatial Graph View 2" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View 2" segmentColormap connect "physics.icol"
"Spatial Graph View 2" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View 2" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View 2" segmentColormap activateLocalRange 1
"Spatial Graph View 2" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View 2" segmentColormap enableAlpha 1
"Spatial Graph View 2" segmentColormap enableAlphaToggle 1
"Spatial Graph View 2" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View 2" fire
"Spatial Graph View 2" nodeOnOff setValue 0
"Spatial Graph View 2" nodeScale setIndex 0 0
"Spatial Graph View 2" fire
"Spatial Graph View 2" nodeScaleFactor setMinMax 0 1
"Spatial Graph View 2" nodeScaleFactor setButtons 0
"Spatial Graph View 2" nodeScaleFactor setEditButton 1
"Spatial Graph View 2" nodeScaleFactor setIncrement 0.0666667
"Spatial Graph View 2" nodeScaleFactor setValue 0.05
"Spatial Graph View 2" nodeScaleFactor setSubMinMax 0 1
"Spatial Graph View 2" nodeColoring setIndex 0 0
"Spatial Graph View 2" nodeLabelColoringOptions setValue 0
"Spatial Graph View 2" nodeColor setColor 0 0.8 0.8 0.8
"Spatial Graph View 2" segmentOnOff setValue 1
"Spatial Graph View 2" segmentStyle setValue 0 1
"Spatial Graph View 2" segmentStyle setToggleVisible 0 1
"Spatial Graph View 2" segmentStyle setValue 1 0
"Spatial Graph View 2" segmentStyle setToggleVisible 1 1
"Spatial Graph View 2" segmentStyle setValue 2 0
"Spatial Graph View 2" segmentStyle setToggleVisible 2 1
"Spatial Graph View 2" tubeScale setIndex 0 0
"Spatial Graph View 2" fire
"Spatial Graph View 2" tubeScaleFactor setMinMax 0 1
"Spatial Graph View 2" tubeScaleFactor setButtons 0
"Spatial Graph View 2" tubeScaleFactor setEditButton 1
"Spatial Graph View 2" tubeScaleFactor setIncrement 0.0666667
"Spatial Graph View 2" tubeScaleFactor setValue 0.05
"Spatial Graph View 2" tubeScaleFactor setSubMinMax 0 1
"Spatial Graph View 2" segmentWidth setMinMax 0 10
"Spatial Graph View 2" segmentWidth setButtons 0
"Spatial Graph View 2" segmentWidth setEditButton 1
"Spatial Graph View 2" segmentWidth setIncrement 0.666667
"Spatial Graph View 2" segmentWidth setValue 10
"Spatial Graph View 2" segmentWidth setSubMinMax 0 10
"Spatial Graph View 2" segmentColoring setIndex 0 0
"Spatial Graph View 2" segmentLabelColoringOptions setValue 0
"Spatial Graph View 2" segmentColor setColor 0 0 0 1
"Spatial Graph View 2" pointSize setMinMax 0 15
"Spatial Graph View 2" pointSize setButtons 0
"Spatial Graph View 2" pointSize setEditButton 1
"Spatial Graph View 2" pointSize setIncrement 1
"Spatial Graph View 2" pointSize setValue 4
"Spatial Graph View 2" pointSize setSubMinMax 0 15
"Spatial Graph View 2" fire
"Spatial Graph View 2" setViewerMask 16383
"Spatial Graph View 2" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "black_L6ct"
"black_L6ct" setIconPosition 404 734
"black_L6ct" setVar "CustomHelp" {HxDisplayLandmarks}
"black_L6ct" setColor 0 0.3 0 0.8
"black_L6ct" setColor 1 0.4 0.63 0.7
"black_L6ct" setColor 2 0.4 0.75 0.11
"black_L6ct" fire
"black_L6ct" chooseSet setIndex 0 0
"black_L6ct" display setValue 0 0
"black_L6ct" display setToggleVisible 0 1
"black_L6ct" drawStyle setValue 0 0
"black_L6ct" drawStyle setToggleVisible 0 1
"black_L6ct" drawStyle setValue 1 0
"black_L6ct" drawStyle setToggleVisible 1 1
"black_L6ct" size setMinMax 0 5
"black_L6ct" size setButtons 0
"black_L6ct" size setEditButton 1
"black_L6ct" size setIncrement 0.333333
"black_L6ct" size setValue 0.4
"black_L6ct" size setSubMinMax 0 5
"black_L6ct" complexity setMinMax 0 1
"black_L6ct" complexity setButtons 0
"black_L6ct" complexity setEditButton 1
"black_L6ct" complexity setIncrement 0.1
"black_L6ct" complexity setValue 0.25
"black_L6ct" complexity setSubMinMax 0 1
"black_L6ct" setBaseSize 321.867
"black_L6ct" fire
"black_L6ct" setViewerMask 16382
"black_L6ct" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "dark_grey_L5tt"
"dark_grey_L5tt" setIconPosition 232 678
"dark_grey_L5tt" setVar "CustomHelp" {HxDisplayLandmarks}
"dark_grey_L5tt" setColor 0 0.45 0.45 0.45
"dark_grey_L5tt" setColor 1 0.4 0.63 0.7
"dark_grey_L5tt" setColor 2 0.4 0.75 0.11
"dark_grey_L5tt" data connect "L5tt.landmarkAscii"
"dark_grey_L5tt" fire
"dark_grey_L5tt" chooseSet setIndex 0 0
"dark_grey_L5tt" display setValue 0 0
"dark_grey_L5tt" display setToggleVisible 0 1
"dark_grey_L5tt" drawStyle setValue 0 0
"dark_grey_L5tt" drawStyle setToggleVisible 0 1
"dark_grey_L5tt" drawStyle setValue 1 0
"dark_grey_L5tt" drawStyle setToggleVisible 1 1
"dark_grey_L5tt" size setMinMax 0 5
"dark_grey_L5tt" size setButtons 0
"dark_grey_L5tt" size setEditButton 1
"dark_grey_L5tt" size setIncrement 0.333333
"dark_grey_L5tt" size setValue 0.4
"dark_grey_L5tt" size setSubMinMax 0 5
"dark_grey_L5tt" complexity setMinMax 0 1
"dark_grey_L5tt" complexity setButtons 0
"dark_grey_L5tt" complexity setEditButton 1
"dark_grey_L5tt" complexity setIncrement 0.1
"dark_grey_L5tt" complexity setValue 0.25
"dark_grey_L5tt" complexity setSubMinMax 0 1
"dark_grey_L5tt" setBaseSize 321.489
"dark_grey_L5tt" fire
"dark_grey_L5tt" setViewerMask 16383
"dark_grey_L5tt" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "yellow_L2"
"yellow_L2" setIconPosition 351 551
"yellow_L2" setVar "CustomHelp" {HxDisplayLandmarks}
"yellow_L2" setColor 0 0.996078 0.929412 0.00392157
"yellow_L2" setColor 1 0.4 0.63 0.7
"yellow_L2" setColor 2 0.4 0.75 0.11
"yellow_L2" fire
"yellow_L2" chooseSet setIndex 0 0
"yellow_L2" display setValue 0 0
"yellow_L2" display setToggleVisible 0 1
"yellow_L2" drawStyle setValue 0 0
"yellow_L2" drawStyle setToggleVisible 0 1
"yellow_L2" drawStyle setValue 1 0
"yellow_L2" drawStyle setToggleVisible 1 1
"yellow_L2" size setMinMax 0 5
"yellow_L2" size setButtons 0
"yellow_L2" size setEditButton 1
"yellow_L2" size setIncrement 0.333333
"yellow_L2" size setValue 0.4
"yellow_L2" size setSubMinMax 0 5
"yellow_L2" complexity setMinMax 0 1
"yellow_L2" complexity setButtons 0
"yellow_L2" complexity setEditButton 1
"yellow_L2" complexity setIncrement 0.1
"yellow_L2" complexity setValue 0.25
"yellow_L2" complexity setSubMinMax 0 1
"yellow_L2" setBaseSize 321.867
"yellow_L2" fire
"yellow_L2" setViewerMask 16382
"yellow_L2" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "light_blue_L5st"
"light_blue_L5st" setIconPosition 364 652
"light_blue_L5st" setVar "CustomHelp" {HxDisplayLandmarks}
"light_blue_L5st" setColor 0 0 0.623529 0.890196
"light_blue_L5st" setColor 1 0.4 0.63 0.7
"light_blue_L5st" setColor 2 0.4 0.75 0.11
"light_blue_L5st" fire
"light_blue_L5st" chooseSet setIndex 0 0
"light_blue_L5st" display setValue 0 0
"light_blue_L5st" display setToggleVisible 0 1
"light_blue_L5st" drawStyle setValue 0 0
"light_blue_L5st" drawStyle setToggleVisible 0 1
"light_blue_L5st" drawStyle setValue 1 0
"light_blue_L5st" drawStyle setToggleVisible 1 1
"light_blue_L5st" size setMinMax 0 5
"light_blue_L5st" size setButtons 0
"light_blue_L5st" size setEditButton 1
"light_blue_L5st" size setIncrement 0.333333
"light_blue_L5st" size setValue 0.4
"light_blue_L5st" size setSubMinMax 0 5
"light_blue_L5st" complexity setMinMax 0 1
"light_blue_L5st" complexity setButtons 0
"light_blue_L5st" complexity setEditButton 1
"light_blue_L5st" complexity setIncrement 0.1
"light_blue_L5st" complexity setValue 0.25
"light_blue_L5st" complexity setSubMinMax 0 1
"light_blue_L5st" setBaseSize 321.867
"light_blue_L5st" fire
"light_blue_L5st" setViewerMask 16382
"light_blue_L5st" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "dark_blue_L5tt"
"dark_blue_L5tt" setIconPosition 406 679
"dark_blue_L5tt" setVar "CustomHelp" {HxDisplayLandmarks}
"dark_blue_L5tt" setColor 0 0 0 1
"dark_blue_L5tt" setColor 1 0.4 0.63 0.7
"dark_blue_L5tt" setColor 2 0.4 0.75 0.11
"dark_blue_L5tt" fire
"dark_blue_L5tt" chooseSet setIndex 0 0
"dark_blue_L5tt" display setValue 0 0
"dark_blue_L5tt" display setToggleVisible 0 1
"dark_blue_L5tt" drawStyle setValue 0 0
"dark_blue_L5tt" drawStyle setToggleVisible 0 1
"dark_blue_L5tt" drawStyle setValue 1 0
"dark_blue_L5tt" drawStyle setToggleVisible 1 1
"dark_blue_L5tt" size setMinMax 0 5
"dark_blue_L5tt" size setButtons 0
"dark_blue_L5tt" size setEditButton 1
"dark_blue_L5tt" size setIncrement 0.333333
"dark_blue_L5tt" size setValue 0.4
"dark_blue_L5tt" size setSubMinMax 0 5
"dark_blue_L5tt" complexity setMinMax 0 1
"dark_blue_L5tt" complexity setButtons 0
"dark_blue_L5tt" complexity setEditButton 1
"dark_blue_L5tt" complexity setIncrement 0.1
"dark_blue_L5tt" complexity setValue 0.25
"dark_blue_L5tt" complexity setSubMinMax 0 1
"dark_blue_L5tt" setBaseSize 321.867
"dark_blue_L5tt" fire
"dark_blue_L5tt" setViewerMask 16382
"dark_blue_L5tt" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "orange_L3py"
"orange_L3py" setIconPosition 360 762
"orange_L3py" setVar "CustomHelp" {HxDisplayLandmarks}
"orange_L3py" setColor 0 1 0.5 0
"orange_L3py" setColor 1 0.4 0.63 0.7
"orange_L3py" setColor 2 0.4 0.75 0.11
"orange_L3py" fire
"orange_L3py" chooseSet setIndex 0 0
"orange_L3py" display setValue 0 0
"orange_L3py" display setToggleVisible 0 1
"orange_L3py" drawStyle setValue 0 0
"orange_L3py" drawStyle setToggleVisible 0 1
"orange_L3py" drawStyle setValue 1 0
"orange_L3py" drawStyle setToggleVisible 1 1
"orange_L3py" size setMinMax 0 5
"orange_L3py" size setButtons 0
"orange_L3py" size setEditButton 1
"orange_L3py" size setIncrement 0.333333
"orange_L3py" size setValue 0.4
"orange_L3py" size setSubMinMax 0 5
"orange_L3py" complexity setMinMax 0 1
"orange_L3py" complexity setButtons 0
"orange_L3py" complexity setEditButton 1
"orange_L3py" complexity setIncrement 0.1
"orange_L3py" complexity setValue 0.25
"orange_L3py" complexity setSubMinMax 0 1
"orange_L3py" setBaseSize 321.867
"orange_L3py" fire
"orange_L3py" setViewerMask 16382
"orange_L3py" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L6cccolor 2"
"L6cccolor 2" setIconPosition 375 704
"L6cccolor 2" setVar "CustomHelp" {HxDisplayLandmarks}
"L6cccolor 2" setColor 0 0.937255 0.623529 0.619608
"L6cccolor 2" setColor 1 0.4 0.63 0.7
"L6cccolor 2" setColor 2 0.4 0.75 0.11
"L6cccolor 2" fire
"L6cccolor 2" chooseSet setIndex 0 0
"L6cccolor 2" display setValue 0 0
"L6cccolor 2" display setToggleVisible 0 1
"L6cccolor 2" drawStyle setValue 0 0
"L6cccolor 2" drawStyle setToggleVisible 0 1
"L6cccolor 2" drawStyle setValue 1 0
"L6cccolor 2" drawStyle setToggleVisible 1 1
"L6cccolor 2" size setMinMax 0 5
"L6cccolor 2" size setButtons 0
"L6cccolor 2" size setEditButton 1
"L6cccolor 2" size setIncrement 0.333333
"L6cccolor 2" size setValue 0.4
"L6cccolor 2" size setSubMinMax 0 5
"L6cccolor 2" complexity setMinMax 0 1
"L6cccolor 2" complexity setButtons 0
"L6cccolor 2" complexity setEditButton 1
"L6cccolor 2" complexity setIncrement 0.1
"L6cccolor 2" complexity setValue 0.25
"L6cccolor 2" complexity setSubMinMax 0 1
"L6cccolor 2" setBaseSize 321.867
"L6cccolor 2" fire
"L6cccolor 2" setViewerMask 16382
"L6cccolor 2" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L6ccinvcolor 2"
"L6ccinvcolor 2" setIconPosition 373 790
"L6ccinvcolor 2" setVar "CustomHelp" {HxDisplayLandmarks}
"L6ccinvcolor 2" setColor 0 0.890196 0.027451 0.0745098
"L6ccinvcolor 2" setColor 1 0.4 0.63 0.7
"L6ccinvcolor 2" setColor 2 0.4 0.75 0.11
"L6ccinvcolor 2" fire
"L6ccinvcolor 2" chooseSet setIndex 0 0
"L6ccinvcolor 2" display setValue 0 0
"L6ccinvcolor 2" display setToggleVisible 0 1
"L6ccinvcolor 2" drawStyle setValue 0 0
"L6ccinvcolor 2" drawStyle setToggleVisible 0 1
"L6ccinvcolor 2" drawStyle setValue 1 0
"L6ccinvcolor 2" drawStyle setToggleVisible 1 1
"L6ccinvcolor 2" size setMinMax 0 5
"L6ccinvcolor 2" size setButtons 0
"L6ccinvcolor 2" size setEditButton 1
"L6ccinvcolor 2" size setIncrement 0.333333
"L6ccinvcolor 2" size setValue 0.4
"L6ccinvcolor 2" size setSubMinMax 0 5
"L6ccinvcolor 2" complexity setMinMax 0 1
"L6ccinvcolor 2" complexity setButtons 0
"L6ccinvcolor 2" complexity setEditButton 1
"L6ccinvcolor 2" complexity setIncrement 0.1
"L6ccinvcolor 2" complexity setValue 0.25
"L6ccinvcolor 2" complexity setSubMinMax 0 1
"L6ccinvcolor 2" setBaseSize 321.867
"L6ccinvcolor 2" fire
"L6ccinvcolor 2" setViewerMask 16382
"L6ccinvcolor 2" setPickable 1

set hideNewModules 0
create HxDisplayVertices "Vertex View"
"Vertex View" setIconPosition 188 -2
"Vertex View" setVar "CustomHelp" {HxDisplayVertices}
"Vertex View" setVar "CustomXML" {HxDisplayVertices_config.xml}
"Vertex View" data connect "EXC.landmarkAscii"
"Vertex View" colormap disconnect
"Vertex View" colormap setDefaultColor 0.7 0.7 0.7
"Vertex View" colormap setDefaultAlpha 1.000000
"Vertex View" colormap activateLocalRange 1
"Vertex View" colormap setLocalMinMax 0.000000 0.000000
"Vertex View" colormap enableAlpha 1
"Vertex View" colormap enableAlphaToggle 1
"Vertex View" colormap setAutoAdjustRangeMode 1
"Vertex View" fire
"Vertex View" color setIndex 0 0
"Vertex View" drawStyle setValue 2
"Vertex View" sphereRadius setMinMax 0 91.3070526123047
"Vertex View" sphereRadius setButtons 0
"Vertex View" sphereRadius setEditButton 1
"Vertex View" sphereRadius setIncrement 6.08714
"Vertex View" sphereRadius setValue 45.6535
"Vertex View" sphereRadius setSubMinMax 0 91.3070526123047
"Vertex View" pointSize setMinMax 1 10
"Vertex View" pointSize setButtons 1
"Vertex View" pointSize setEditButton 1
"Vertex View" pointSize setIncrement 1
"Vertex View" pointSize setValue 4
"Vertex View" pointSize setSubMinMax 1 10
"Vertex View" complexity setMinMax 0 1
"Vertex View" complexity setButtons 0
"Vertex View" complexity setEditButton 1
"Vertex View" complexity setIncrement 0.1
"Vertex View" complexity setValue 0.2
"Vertex View" complexity setSubMinMax 0 1
"Vertex View" textOnOff setValue 0
"Vertex View" transparentOnOff setValue 0
"Vertex View" displaySelectionOnOff setValue 0
"Vertex View" fontSize setMinMax 5 50
"Vertex View" fontSize setButtons 1
"Vertex View" fontSize setEditButton 1
"Vertex View" fontSize setIncrement 1
"Vertex View" fontSize setValue 15
"Vertex View" fontSize setSubMinMax 5 50
"Vertex View" transparency setMinMax 0 1
"Vertex View" transparency setButtons 0
"Vertex View" transparency setEditButton 1
"Vertex View" transparency setIncrement 0.1
"Vertex View" transparency setValue 0.5
"Vertex View" transparency setSubMinMax 0 1
"Vertex View" setTextColor 1 1 1
"Vertex View" pointStarts0
"Vertex View" fire
"Vertex View" drawStyle setValue 2
"Vertex View" setColor 0 24263 0.700000 0.700000 0.700000
"Vertex View" fire
"Vertex View" setViewerMask 8191
"Vertex View" setPickable 1

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View 3"
"Spatial Graph View 3" setIconPosition 188 33
"Spatial Graph View 3" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View 3" setVar "CustomXML" {HxSpatialGraphView_config.xml}
"Spatial Graph View 3" data connect "morphology.hoc"
"Spatial Graph View 3" nodeColormap connect "physics.icol"
"Spatial Graph View 3" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View 3" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View 3" nodeColormap activateLocalRange 1
"Spatial Graph View 3" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View 3" nodeColormap enableAlpha 1
"Spatial Graph View 3" nodeColormap enableAlphaToggle 1
"Spatial Graph View 3" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View 3" segmentColormap connect "physics.icol"
"Spatial Graph View 3" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View 3" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View 3" segmentColormap activateLocalRange 1
"Spatial Graph View 3" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View 3" segmentColormap enableAlpha 1
"Spatial Graph View 3" segmentColormap enableAlphaToggle 1
"Spatial Graph View 3" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View 3" fire
"Spatial Graph View 3" nodeOnOff setValue 0
"Spatial Graph View 3" nodeScale setIndex 0 0
"Spatial Graph View 3" fire
"Spatial Graph View 3" nodeScaleFactor setMinMax 0 1
"Spatial Graph View 3" nodeScaleFactor setButtons 0
"Spatial Graph View 3" nodeScaleFactor setEditButton 1
"Spatial Graph View 3" nodeScaleFactor setIncrement 0.1
"Spatial Graph View 3" nodeScaleFactor setValue 0.1
"Spatial Graph View 3" nodeScaleFactor setSubMinMax 0 1
"Spatial Graph View 3" nodeColoring setIndex 0 0
"Spatial Graph View 3" nodeLabelColoringOptions setValue 0
"Spatial Graph View 3" nodeColor setColor 0 0 0 0
"Spatial Graph View 3" segmentOnOff setValue 1
"Spatial Graph View 3" segmentStyle setValue 0 0
"Spatial Graph View 3" segmentStyle setToggleVisible 0 1
"Spatial Graph View 3" segmentStyle setValue 1 0
"Spatial Graph View 3" segmentStyle setToggleVisible 1 1
"Spatial Graph View 3" segmentStyle setValue 2 1
"Spatial Graph View 3" segmentStyle setToggleVisible 2 1
"Spatial Graph View 3" tubeScale setIndex 0 2
"Spatial Graph View 3" fire
"Spatial Graph View 3" tubeScaleFactor setMinMax 0 10
"Spatial Graph View 3" tubeScaleFactor setButtons 0
"Spatial Graph View 3" tubeScaleFactor setEditButton 1
"Spatial Graph View 3" tubeScaleFactor setIncrement 0.666667
"Spatial Graph View 3" tubeScaleFactor setValue 1.4966
"Spatial Graph View 3" tubeScaleFactor setSubMinMax 0 10
"Spatial Graph View 3" segmentWidth setMinMax 0 10
"Spatial Graph View 3" segmentWidth setButtons 0
"Spatial Graph View 3" segmentWidth setEditButton 1
"Spatial Graph View 3" segmentWidth setIncrement 0.666667
"Spatial Graph View 3" segmentWidth setValue 1
"Spatial Graph View 3" segmentWidth setSubMinMax 0 10
"Spatial Graph View 3" segmentColoring setIndex 0 0
"Spatial Graph View 3" segmentLabelColoringOptions setValue 0
"Spatial Graph View 3" segmentColor setColor 0 0 0 0
"Spatial Graph View 3" pointSize setMinMax 0 15
"Spatial Graph View 3" pointSize setButtons 0
"Spatial Graph View 3" pointSize setEditButton 1
"Spatial Graph View 3" pointSize setIncrement 1
"Spatial Graph View 3" pointSize setValue 4
"Spatial Graph View 3" pointSize setSubMinMax 0 15
"Spatial Graph View 3" setVisibility HIJMPLPPBPBFAAAAIHIIAPPB HIJMPLPPBPBFAAAAIHIIAPPB
"Spatial Graph View 3" fire
"Spatial Graph View 3" setViewerMask 8191
"Spatial Graph View 3" setPickable 1

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View 4"
"Spatial Graph View 4" setIconPosition 228 67
"Spatial Graph View 4" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View 4" setVar "CustomXML" {HxSpatialGraphView_config.xml}
"Spatial Graph View 4" data connect "morphology_no_soma.hoc"
"Spatial Graph View 4" nodeColormap connect "physics.icol"
"Spatial Graph View 4" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View 4" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View 4" nodeColormap activateLocalRange 1
"Spatial Graph View 4" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View 4" nodeColormap enableAlpha 1
"Spatial Graph View 4" nodeColormap enableAlphaToggle 1
"Spatial Graph View 4" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View 4" segmentColormap connect "physics.icol"
"Spatial Graph View 4" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View 4" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View 4" segmentColormap activateLocalRange 1
"Spatial Graph View 4" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View 4" segmentColormap enableAlpha 1
"Spatial Graph View 4" segmentColormap enableAlphaToggle 1
"Spatial Graph View 4" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View 4" fire
"Spatial Graph View 4" nodeOnOff setValue 0
"Spatial Graph View 4" nodeScale setIndex 0 0
"Spatial Graph View 4" fire
"Spatial Graph View 4" nodeScaleFactor setMinMax 0 1
"Spatial Graph View 4" nodeScaleFactor setButtons 0
"Spatial Graph View 4" nodeScaleFactor setEditButton 1
"Spatial Graph View 4" nodeScaleFactor setIncrement 0.1
"Spatial Graph View 4" nodeScaleFactor setValue 0.1
"Spatial Graph View 4" nodeScaleFactor setSubMinMax 0 1
"Spatial Graph View 4" nodeColoring setIndex 0 0
"Spatial Graph View 4" nodeLabelColoringOptions setValue 0
"Spatial Graph View 4" nodeColor setColor 0 0 0 0
"Spatial Graph View 4" segmentOnOff setValue 1
"Spatial Graph View 4" segmentStyle setValue 0 0
"Spatial Graph View 4" segmentStyle setToggleVisible 0 1
"Spatial Graph View 4" segmentStyle setValue 1 0
"Spatial Graph View 4" segmentStyle setToggleVisible 1 1
"Spatial Graph View 4" segmentStyle setValue 2 1
"Spatial Graph View 4" segmentStyle setToggleVisible 2 1
"Spatial Graph View 4" tubeScale setIndex 0 2
"Spatial Graph View 4" fire
"Spatial Graph View 4" tubeScaleFactor setMinMax 0 10
"Spatial Graph View 4" tubeScaleFactor setButtons 0
"Spatial Graph View 4" tubeScaleFactor setEditButton 1
"Spatial Graph View 4" tubeScaleFactor setIncrement 0.666667
"Spatial Graph View 4" tubeScaleFactor setValue 3.5
"Spatial Graph View 4" tubeScaleFactor setSubMinMax 0 10
"Spatial Graph View 4" segmentWidth setMinMax 0 10
"Spatial Graph View 4" segmentWidth setButtons 0
"Spatial Graph View 4" segmentWidth setEditButton 1
"Spatial Graph View 4" segmentWidth setIncrement 0.666667
"Spatial Graph View 4" segmentWidth setValue 1
"Spatial Graph View 4" segmentWidth setSubMinMax 0 10
"Spatial Graph View 4" segmentColoring setIndex 0 0
"Spatial Graph View 4" segmentLabelColoringOptions setValue 0
"Spatial Graph View 4" segmentColor setColor 0 0 0 0
"Spatial Graph View 4" pointSize setMinMax 0 15
"Spatial Graph View 4" pointSize setButtons 0
"Spatial Graph View 4" pointSize setEditButton 1
"Spatial Graph View 4" pointSize setIncrement 1
"Spatial Graph View 4" pointSize setValue 4
"Spatial Graph View 4" pointSize setSubMinMax 0 15
"Spatial Graph View 4" setVisibility HIJMPLPPBPBFAAAAIHIIAPPB HIJMPLPPBPBFAAAAIHIIAPPB
"Spatial Graph View 4" fire
"Spatial Graph View 4" setViewerMask 8191
"Spatial Graph View 4" setPickable 1

set hideNewModules 0

viewer 0 setCameraOrientation 0.391947 0.679242 0.62049 2.37879
viewer 0 setCameraPosition 1509.44 802.209 -489.014
viewer 0 setCameraFocalDistance 1579.11
viewer 0 setCameraNearDistance -1410.55
viewer 0 setCameraFarDistance 3656.85
viewer 0 setCameraType orthographic
viewer 0 setCameraHeight 2485.99
viewer 0 setAutoRedraw 1
viewer 0 redraw

correlationPanel closeTabs
correlationPanel setTabName 0 "Correlation 1"
correlationPanel 0 setLogScalingOnAxis 0 0
correlationPanel 0 setLogScalingOnAxis 1 0

histogramPanel closeTabs
histogramPanel setTabName 0 "Histogram 1"
histogramPanel 0 setLogScalingOnAxis 0 0
histogramPanel 0 setLogScalingOnAxis 1 1

