# Amira Project 202020
# AmiraZIBEdition
# Generated by AmiraZIBEdition 2020.38
remove -all
remove "temperature.icol" "physics.icol" "INH.landmarkAscii" "L2.landmarkAscii" "L4py.landmarkAscii" "L4sp.landmarkAscii" "L4ss.landmarkAscii" "L5st.landmarkAscii" "L5tt.landmarkAscii" "L6ccinv.landmarkAscii" "L6cc.landmarkAscii" "L6ct.landmarkAscii" "L34.landmarkAscii" "VPM.landmarkAscii" "morphology.hoc" "morphology_no_soma.hoc" "Spatial Graph View" "L2color" "L4pycolor" "L4spcolor" "L4sscolor" "L5stcolor" "L5ttcolor" "L6ccinvcolor" "L6ctcolor" "L34color" "L6cccolor" "Spatial Graph View 2" "VPMcolor"

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 5
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show

_units setUnitsManagementMode 0

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/temperature.icol ] setLabel "temperature.icol"
"temperature.icol" setIconPosition 0 0
"temperature.icol" setNoRemoveAll 1
"temperature.icol" fire
"temperature.icol" setMinMax 38 44
"temperature.icol" flags setValue 1
"temperature.icol" shift setMinMax -1 1
"temperature.icol" shift setButtons 0
"temperature.icol" shift setEditButton 1
"temperature.icol" shift setIncrement 0.133333
"temperature.icol" shift setValue 0
"temperature.icol" shift setSubMinMax -1 1
"temperature.icol" scale setMinMax 0 1
"temperature.icol" scale setButtons 0
"temperature.icol" scale setEditButton 1
"temperature.icol" scale setIncrement 0.1
"temperature.icol" scale setValue 1
"temperature.icol" scale setSubMinMax 0 1
"temperature.icol" fire
"temperature.icol" setViewerMask 8191

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/physics.icol ] setLabel "physics.icol"
"physics.icol" setIconPosition 0 0
"physics.icol" setNoRemoveAll 1
"physics.icol" fire
"physics.icol" setMinMax 0 1
"physics.icol" flags setValue 1
"physics.icol" shift setMinMax -1 1
"physics.icol" shift setButtons 0
"physics.icol" shift setEditButton 1
"physics.icol" shift setIncrement 0.133333
"physics.icol" shift setValue 0
"physics.icol" shift setSubMinMax -1 1
"physics.icol" scale setMinMax 0 1
"physics.icol" scale setButtons 0
"physics.icol" scale setEditButton 1
"physics.icol" scale setIncrement 0.1
"physics.icol" scale setValue 1
"physics.icol" scale setSubMinMax 0 1
"physics.icol" fire
"physics.icol" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/all_synapses/1/INH.landmarkAscii ] setLabel "INH.landmarkAscii"
"INH.landmarkAscii" setIconPosition 20 -205
"INH.landmarkAscii" fire
"INH.landmarkAscii" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/all_synapses/1/L2.landmarkAscii ] setLabel "L2.landmarkAscii"
"L2.landmarkAscii" setIconPosition 137 577
"L2.landmarkAscii" fire
"L2.landmarkAscii" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/all_synapses/1/L4py.landmarkAscii ] setLabel "L4py.landmarkAscii"
"L4py.landmarkAscii" setIconPosition 136 604
"L4py.landmarkAscii" fire
"L4py.landmarkAscii" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/all_synapses/1/L4sp.landmarkAscii ] setLabel "L4sp.landmarkAscii"
"L4sp.landmarkAscii" setIconPosition 135 632
"L4sp.landmarkAscii" fire
"L4sp.landmarkAscii" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/all_synapses/1/L4ss.landmarkAscii ] setLabel "L4ss.landmarkAscii"
"L4ss.landmarkAscii" setIconPosition 132 661
"L4ss.landmarkAscii" fire
"L4ss.landmarkAscii" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/all_synapses/1/L5st.landmarkAscii ] setLabel "L5st.landmarkAscii"
"L5st.landmarkAscii" setIconPosition 136 692
"L5st.landmarkAscii" fire
"L5st.landmarkAscii" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/all_synapses/1/L5tt.landmarkAscii ] setLabel "L5tt.landmarkAscii"
"L5tt.landmarkAscii" setIconPosition 135 726
"L5tt.landmarkAscii" fire
"L5tt.landmarkAscii" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/all_synapses/1/L6ccinv.landmarkAscii ] setLabel "L6ccinv.landmarkAscii"
"L6ccinv.landmarkAscii" setIconPosition 134 757
"L6ccinv.landmarkAscii" fire
"L6ccinv.landmarkAscii" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/all_synapses/1/L6cc.landmarkAscii ] setLabel "L6cc.landmarkAscii"
"L6cc.landmarkAscii" setIconPosition 135 784
"L6cc.landmarkAscii" fire
"L6cc.landmarkAscii" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/all_synapses/1/L6ct.landmarkAscii ] setLabel "L6ct.landmarkAscii"
"L6ct.landmarkAscii" setIconPosition 135 813
"L6ct.landmarkAscii" fire
"L6ct.landmarkAscii" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/all_synapses/1/L34.landmarkAscii ] setLabel "L34.landmarkAscii"
"L34.landmarkAscii" setIconPosition 135 840
"L34.landmarkAscii" fire
"L34.landmarkAscii" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/all_synapses/1/VPM.landmarkAscii ] setLabel "VPM.landmarkAscii"
"VPM.landmarkAscii" setIconPosition 135 869
"VPM.landmarkAscii" fire
"VPM.landmarkAscii" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/anatomy/morphology.hoc ] setLabel "morphology.hoc"
"morphology.hoc" setIconPosition 162 952
"morphology.hoc" setVar "CustomXML" {morphology.hoc_config.xml}
"morphology.hoc" fire
"morphology.hoc" fire
"morphology.hoc" setViewerMask 8191

set hideNewModules 0
[ load ${SCRIPTDIR}/anatomy/morphology_no_soma.hoc ] setLabel "morphology_no_soma.hoc"
"morphology_no_soma.hoc" setIconPosition 113 990
"morphology_no_soma.hoc" setVar "CustomXML" {morphology_no_soma.hoc_config.xml}
"morphology_no_soma.hoc" fire
"morphology_no_soma.hoc" fire
"morphology_no_soma.hoc" setViewerMask 8191

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View"
"Spatial Graph View" setIconPosition 347 985
"Spatial Graph View" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View" data connect "morphology_no_soma.hoc"
"Spatial Graph View" nodeColormap connect "physics.icol"
"Spatial Graph View" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View" nodeColormap activateLocalRange 1
"Spatial Graph View" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" nodeColormap enableAlpha 1
"Spatial Graph View" nodeColormap enableAlphaToggle 1
"Spatial Graph View" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View" segmentColormap connect "physics.icol"
"Spatial Graph View" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View" segmentColormap activateLocalRange 1
"Spatial Graph View" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" segmentColormap enableAlpha 1
"Spatial Graph View" segmentColormap enableAlphaToggle 1
"Spatial Graph View" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View" fire
"Spatial Graph View" nodeOnOff setValue 0
"Spatial Graph View" nodeScale setIndex 0 0
"Spatial Graph View" fire
"Spatial Graph View" nodeScaleFactor setMinMax 0 1
"Spatial Graph View" nodeScaleFactor setButtons 0
"Spatial Graph View" nodeScaleFactor setEditButton 1
"Spatial Graph View" nodeScaleFactor setIncrement 0.0666667
"Spatial Graph View" nodeScaleFactor setValue 0.1
"Spatial Graph View" nodeScaleFactor setSubMinMax 0 119.735794067383
"Spatial Graph View" nodeColoring setIndex 0 0
"Spatial Graph View" nodeLabelColoringOptions setValue 0
"Spatial Graph View" nodeColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" segmentOnOff setValue 1
"Spatial Graph View" segmentStyle setValue 0 0
"Spatial Graph View" segmentStyle setToggleVisible 0 1
"Spatial Graph View" segmentStyle setValue 1 0
"Spatial Graph View" segmentStyle setToggleVisible 1 1
"Spatial Graph View" segmentStyle setValue 2 1
"Spatial Graph View" segmentStyle setToggleVisible 2 1
"Spatial Graph View" tubeScale setIndex 0 0
"Spatial Graph View" fire
"Spatial Graph View" tubeScaleFactor setMinMax 0 1
"Spatial Graph View" tubeScaleFactor setButtons 0
"Spatial Graph View" tubeScaleFactor setEditButton 1
"Spatial Graph View" tubeScaleFactor setIncrement 0.0666667
"Spatial Graph View" tubeScaleFactor setValue 0.1
"Spatial Graph View" tubeScaleFactor setSubMinMax 0 7.89647245407104
"Spatial Graph View" segmentWidth setMinMax 0 10
"Spatial Graph View" segmentWidth setButtons 0
"Spatial Graph View" segmentWidth setEditButton 1
"Spatial Graph View" segmentWidth setIncrement 0.666667
"Spatial Graph View" segmentWidth setValue 1
"Spatial Graph View" segmentWidth setSubMinMax 0 10
"Spatial Graph View" segmentColoring setIndex 0 0
"Spatial Graph View" segmentLabelColoringOptions setValue 0
"Spatial Graph View" segmentColor setColor 0 0 0 0
"Spatial Graph View" pointSize setMinMax 0 15
"Spatial Graph View" pointSize setButtons 0
"Spatial Graph View" pointSize setEditButton 1
"Spatial Graph View" pointSize setIncrement 1
"Spatial Graph View" pointSize setValue 4
"Spatial Graph View" pointSize setSubMinMax 0 15
"Spatial Graph View" setVisibility HIJMPLPPBPBFAAAAIHIIAPPB HIJMPLPPBPBFAAAAIHIIAPPB
"Spatial Graph View" fire
"Spatial Graph View" setViewerMask 16383
"Spatial Graph View" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L2color"
"L2color" setIconPosition 322 577
"L2color" setVar "CustomHelp" {HxDisplayLandmarks}
"L2color" setVar "CustomXML" {HxDisplayLandmarks_config.xml}
"L2color" setColor 0 0 0.623529 0.890196
"L2color" setColor 1 0.4 0.63 0.7
"L2color" setColor 2 0.4 0.75 0.11
"L2color" data connect "L2.landmarkAscii"
"L2color" fire
"L2color" chooseSet setIndex 0 0
"L2color" display setValue 0 0
"L2color" display setToggleVisible 0 1
"L2color" drawStyle setValue 0 0
"L2color" drawStyle setToggleVisible 0 1
"L2color" drawStyle setValue 1 0
"L2color" drawStyle setToggleVisible 1 1
"L2color" size setMinMax 0 5
"L2color" size setButtons 0
"L2color" size setEditButton 1
"L2color" size setIncrement 0.333333
"L2color" size setValue 0.6
"L2color" size setSubMinMax 0 5
"L2color" complexity setMinMax 0 1
"L2color" complexity setButtons 0
"L2color" complexity setEditButton 1
"L2color" complexity setIncrement 0.1
"L2color" complexity setValue 0.25
"L2color" complexity setSubMinMax 0 1
"L2color" setBaseSize 127.248
"L2color" fire
"L2color" setViewerMask 16383
"L2color" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L4pycolor"
"L4pycolor" setIconPosition 331 602
"L4pycolor" setVar "CustomHelp" {HxDisplayLandmarks}
"L4pycolor" setVar "CustomXML" {HxDisplayLandmarks_config.xml}
"L4pycolor" setColor 0 0.572549 0.866667 0.501961
"L4pycolor" setColor 1 0.4 0.63 0.7
"L4pycolor" setColor 2 0.4 0.75 0.11
"L4pycolor" data connect "L4py.landmarkAscii"
"L4pycolor" fire
"L4pycolor" chooseSet setIndex 0 0
"L4pycolor" display setValue 0 0
"L4pycolor" display setToggleVisible 0 1
"L4pycolor" drawStyle setValue 0 0
"L4pycolor" drawStyle setToggleVisible 0 1
"L4pycolor" drawStyle setValue 1 0
"L4pycolor" drawStyle setToggleVisible 1 1
"L4pycolor" size setMinMax 0 5
"L4pycolor" size setButtons 0
"L4pycolor" size setEditButton 1
"L4pycolor" size setIncrement 0.333333
"L4pycolor" size setValue 0.6
"L4pycolor" size setSubMinMax 0 5
"L4pycolor" complexity setMinMax 0 1
"L4pycolor" complexity setButtons 0
"L4pycolor" complexity setEditButton 1
"L4pycolor" complexity setIncrement 0.1
"L4pycolor" complexity setValue 0.25
"L4pycolor" complexity setSubMinMax 0 1
"L4pycolor" setBaseSize 127.248
"L4pycolor" fire
"L4pycolor" setViewerMask 16383
"L4pycolor" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L4spcolor"
"L4spcolor" setIconPosition 336 627
"L4spcolor" setVar "CustomHelp" {HxDisplayLandmarks}
"L4spcolor" setVar "CustomXML" {HxDisplayLandmarks_config.xml}
"L4spcolor" setColor 0 0.396078 0.709804 0.423529
"L4spcolor" setColor 1 0.4 0.63 0.7
"L4spcolor" setColor 2 0.4 0.75 0.11
"L4spcolor" data connect "L4sp.landmarkAscii"
"L4spcolor" fire
"L4spcolor" chooseSet setIndex 0 0
"L4spcolor" display setValue 0 0
"L4spcolor" display setToggleVisible 0 1
"L4spcolor" drawStyle setValue 0 0
"L4spcolor" drawStyle setToggleVisible 0 1
"L4spcolor" drawStyle setValue 1 0
"L4spcolor" drawStyle setToggleVisible 1 1
"L4spcolor" size setMinMax 0 5
"L4spcolor" size setButtons 0
"L4spcolor" size setEditButton 1
"L4spcolor" size setIncrement 0.333333
"L4spcolor" size setValue 0.6
"L4spcolor" size setSubMinMax 0 5
"L4spcolor" complexity setMinMax 0 1
"L4spcolor" complexity setButtons 0
"L4spcolor" complexity setEditButton 1
"L4spcolor" complexity setIncrement 0.1
"L4spcolor" complexity setValue 0.25
"L4spcolor" complexity setSubMinMax 0 1
"L4spcolor" setBaseSize 127.248
"L4spcolor" fire
"L4spcolor" setViewerMask 16383
"L4spcolor" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L4sscolor"
"L4sscolor" setIconPosition 328 657
"L4sscolor" setVar "CustomHelp" {HxDisplayLandmarks}
"L4sscolor" setVar "CustomXML" {HxDisplayLandmarks_config.xml}
"L4sscolor" setColor 0 0.396078 0.709804 0.423529
"L4sscolor" setColor 1 0.4 0.63 0.7
"L4sscolor" setColor 2 0.4 0.75 0.11
"L4sscolor" data connect "L4ss.landmarkAscii"
"L4sscolor" fire
"L4sscolor" chooseSet setIndex 0 0
"L4sscolor" display setValue 0 0
"L4sscolor" display setToggleVisible 0 1
"L4sscolor" drawStyle setValue 0 0
"L4sscolor" drawStyle setToggleVisible 0 1
"L4sscolor" drawStyle setValue 1 0
"L4sscolor" drawStyle setToggleVisible 1 1
"L4sscolor" size setMinMax 0 5
"L4sscolor" size setButtons 0
"L4sscolor" size setEditButton 1
"L4sscolor" size setIncrement 0.333333
"L4sscolor" size setValue 0.6
"L4sscolor" size setSubMinMax 0 5
"L4sscolor" complexity setMinMax 0 1
"L4sscolor" complexity setButtons 0
"L4sscolor" complexity setEditButton 1
"L4sscolor" complexity setIncrement 0.1
"L4sscolor" complexity setValue 0.25
"L4sscolor" complexity setSubMinMax 0 1
"L4sscolor" setBaseSize 127.248
"L4sscolor" fire
"L4sscolor" setViewerMask 16383
"L4sscolor" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L5stcolor"
"L5stcolor" setIconPosition 329 686
"L5stcolor" setVar "CustomHelp" {HxDisplayLandmarks}
"L5stcolor" setVar "CustomXML" {HxDisplayLandmarks_config.xml}
"L5stcolor" setColor 0 0.996078 0.929412 0.00392157
"L5stcolor" setColor 1 0.4 0.63 0.7
"L5stcolor" setColor 2 0.4 0.75 0.11
"L5stcolor" data connect "L5st.landmarkAscii"
"L5stcolor" fire
"L5stcolor" chooseSet setIndex 0 0
"L5stcolor" display setValue 0 0
"L5stcolor" display setToggleVisible 0 1
"L5stcolor" drawStyle setValue 0 0
"L5stcolor" drawStyle setToggleVisible 0 1
"L5stcolor" drawStyle setValue 1 0
"L5stcolor" drawStyle setToggleVisible 1 1
"L5stcolor" size setMinMax 0 5
"L5stcolor" size setButtons 0
"L5stcolor" size setEditButton 1
"L5stcolor" size setIncrement 0.333333
"L5stcolor" size setValue 0.6
"L5stcolor" size setSubMinMax 0 5
"L5stcolor" complexity setMinMax 0 1
"L5stcolor" complexity setButtons 0
"L5stcolor" complexity setEditButton 1
"L5stcolor" complexity setIncrement 0.1
"L5stcolor" complexity setValue 0.25
"L5stcolor" complexity setSubMinMax 0 1
"L5stcolor" setBaseSize 127.248
"L5stcolor" fire
"L5stcolor" setViewerMask 16383
"L5stcolor" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L5ttcolor"
"L5ttcolor" setIconPosition 330 722
"L5ttcolor" setVar "CustomHelp" {HxDisplayLandmarks}
"L5ttcolor" setVar "CustomXML" {HxDisplayLandmarks_config.xml}
"L5ttcolor" setColor 0 0.45 0.45 0.45
"L5ttcolor" setColor 1 0.4 0.63 0.7
"L5ttcolor" setColor 2 0.4 0.75 0.11
"L5ttcolor" data connect "L5tt.landmarkAscii"
"L5ttcolor" fire
"L5ttcolor" chooseSet setIndex 0 0
"L5ttcolor" display setValue 0 0
"L5ttcolor" display setToggleVisible 0 1
"L5ttcolor" drawStyle setValue 0 0
"L5ttcolor" drawStyle setToggleVisible 0 1
"L5ttcolor" drawStyle setValue 1 0
"L5ttcolor" drawStyle setToggleVisible 1 1
"L5ttcolor" size setMinMax 0 5
"L5ttcolor" size setButtons 0
"L5ttcolor" size setEditButton 1
"L5ttcolor" size setIncrement 0.333333
"L5ttcolor" size setValue 0.6
"L5ttcolor" size setSubMinMax 0 5
"L5ttcolor" complexity setMinMax 0 1
"L5ttcolor" complexity setButtons 0
"L5ttcolor" complexity setEditButton 1
"L5ttcolor" complexity setIncrement 0.1
"L5ttcolor" complexity setValue 0.25
"L5ttcolor" complexity setSubMinMax 0 1
"L5ttcolor" setBaseSize 127.248
"L5ttcolor" fire
"L5ttcolor" setViewerMask 16383
"L5ttcolor" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L6ccinvcolor"
"L6ccinvcolor" setIconPosition 331 758
"L6ccinvcolor" setVar "CustomHelp" {HxDisplayLandmarks}
"L6ccinvcolor" setVar "CustomXML" {HxDisplayLandmarks_config.xml}
"L6ccinvcolor" setColor 0 0.890196 0.027451 0.0745098
"L6ccinvcolor" setColor 1 0.4 0.63 0.7
"L6ccinvcolor" setColor 2 0.4 0.75 0.11
"L6ccinvcolor" data connect "L6ccinv.landmarkAscii"
"L6ccinvcolor" fire
"L6ccinvcolor" chooseSet setIndex 0 0
"L6ccinvcolor" display setValue 0 0
"L6ccinvcolor" display setToggleVisible 0 1
"L6ccinvcolor" drawStyle setValue 0 0
"L6ccinvcolor" drawStyle setToggleVisible 0 1
"L6ccinvcolor" drawStyle setValue 1 0
"L6ccinvcolor" drawStyle setToggleVisible 1 1
"L6ccinvcolor" size setMinMax 0 5
"L6ccinvcolor" size setButtons 0
"L6ccinvcolor" size setEditButton 1
"L6ccinvcolor" size setIncrement 0.333333
"L6ccinvcolor" size setValue 0.6
"L6ccinvcolor" size setSubMinMax 0 5
"L6ccinvcolor" complexity setMinMax 0 1
"L6ccinvcolor" complexity setButtons 0
"L6ccinvcolor" complexity setEditButton 1
"L6ccinvcolor" complexity setIncrement 0.1
"L6ccinvcolor" complexity setValue 0.25
"L6ccinvcolor" complexity setSubMinMax 0 1
"L6ccinvcolor" setBaseSize 127.248
"L6ccinvcolor" fire
"L6ccinvcolor" setViewerMask 16383
"L6ccinvcolor" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L6ctcolor"
"L6ctcolor" setIconPosition 332 787
"L6ctcolor" setVar "CustomHelp" {HxDisplayLandmarks}
"L6ctcolor" setVar "CustomXML" {HxDisplayLandmarks_config.xml}
"L6ctcolor" setColor 0 0.55 0 1
"L6ctcolor" setColor 1 0.4 0.63 0.7
"L6ctcolor" setColor 2 0.4 0.75 0.11
"L6ctcolor" data connect "L6cc.landmarkAscii"
"L6ctcolor" fire
"L6ctcolor" chooseSet setIndex 0 0
"L6ctcolor" display setValue 0 0
"L6ctcolor" display setToggleVisible 0 1
"L6ctcolor" drawStyle setValue 0 0
"L6ctcolor" drawStyle setToggleVisible 0 1
"L6ctcolor" drawStyle setValue 1 0
"L6ctcolor" drawStyle setToggleVisible 1 1
"L6ctcolor" size setMinMax 0 5
"L6ctcolor" size setButtons 0
"L6ctcolor" size setEditButton 1
"L6ctcolor" size setIncrement 0.333333
"L6ctcolor" size setValue 0.6
"L6ctcolor" size setSubMinMax 0 5
"L6ctcolor" complexity setMinMax 0 1
"L6ctcolor" complexity setButtons 0
"L6ctcolor" complexity setEditButton 1
"L6ctcolor" complexity setIncrement 0.1
"L6ctcolor" complexity setValue 0.25
"L6ctcolor" complexity setSubMinMax 0 1
"L6ctcolor" setBaseSize 127.248
"L6ctcolor" fire
"L6ctcolor" setViewerMask 16383
"L6ctcolor" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L34color"
"L34color" setIconPosition 339 844
"L34color" setVar "CustomHelp" {HxDisplayLandmarks}
"L34color" setVar "CustomXML" {HxDisplayLandmarks_config.xml}
"L34color" setColor 0 0.0470588 0 1
"L34color" setColor 1 0.4 0.63 0.7
"L34color" setColor 2 0.4 0.75 0.11
"L34color" data connect "L34.landmarkAscii"
"L34color" fire
"L34color" chooseSet setIndex 0 0
"L34color" display setValue 0 0
"L34color" display setToggleVisible 0 1
"L34color" drawStyle setValue 0 0
"L34color" drawStyle setToggleVisible 0 1
"L34color" drawStyle setValue 1 0
"L34color" drawStyle setToggleVisible 1 1
"L34color" size setMinMax 0 5
"L34color" size setButtons 0
"L34color" size setEditButton 1
"L34color" size setIncrement 0.333333
"L34color" size setValue 0.6
"L34color" size setSubMinMax 0 5
"L34color" complexity setMinMax 0 1
"L34color" complexity setButtons 0
"L34color" complexity setEditButton 1
"L34color" complexity setIncrement 0.1
"L34color" complexity setValue 0.25
"L34color" complexity setSubMinMax 0 1
"L34color" setBaseSize 127.248
"L34color" fire
"L34color" setViewerMask 16383
"L34color" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "L6cccolor"
"L6cccolor" setIconPosition 339 815
"L6cccolor" setVar "CustomHelp" {HxDisplayLandmarks}
"L6cccolor" setVar "CustomXML" {HxDisplayLandmarks_config.xml}
"L6cccolor" setColor 0 0.937255 0.623529 0.619608
"L6cccolor" setColor 1 0.4 0.63 0.7
"L6cccolor" setColor 2 0.4 0.75 0.11
"L6cccolor" data connect "L6ct.landmarkAscii"
"L6cccolor" fire
"L6cccolor" chooseSet setIndex 0 0
"L6cccolor" display setValue 0 0
"L6cccolor" display setToggleVisible 0 1
"L6cccolor" drawStyle setValue 0 0
"L6cccolor" drawStyle setToggleVisible 0 1
"L6cccolor" drawStyle setValue 1 0
"L6cccolor" drawStyle setToggleVisible 1 1
"L6cccolor" size setMinMax 0 5
"L6cccolor" size setButtons 0
"L6cccolor" size setEditButton 1
"L6cccolor" size setIncrement 0.333333
"L6cccolor" size setValue 0.6
"L6cccolor" size setSubMinMax 0 5
"L6cccolor" complexity setMinMax 0 1
"L6cccolor" complexity setButtons 0
"L6cccolor" complexity setEditButton 1
"L6cccolor" complexity setIncrement 0.1
"L6cccolor" complexity setValue 0.25
"L6cccolor" complexity setSubMinMax 0 1
"L6cccolor" setBaseSize 127.248
"L6cccolor" fire
"L6cccolor" setViewerMask 16383
"L6cccolor" setPickable 1

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View 2"
"Spatial Graph View 2" setIconPosition 349 948
"Spatial Graph View 2" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View 2" data connect "morphology.hoc"
"Spatial Graph View 2" nodeColormap connect "physics.icol"
"Spatial Graph View 2" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View 2" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View 2" nodeColormap activateLocalRange 1
"Spatial Graph View 2" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View 2" nodeColormap enableAlpha 1
"Spatial Graph View 2" nodeColormap enableAlphaToggle 1
"Spatial Graph View 2" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View 2" segmentColormap connect "physics.icol"
"Spatial Graph View 2" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View 2" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View 2" segmentColormap activateLocalRange 1
"Spatial Graph View 2" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View 2" segmentColormap enableAlpha 1
"Spatial Graph View 2" segmentColormap enableAlphaToggle 1
"Spatial Graph View 2" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View 2" fire
"Spatial Graph View 2" nodeOnOff setValue 0
"Spatial Graph View 2" nodeScale setIndex 0 0
"Spatial Graph View 2" fire
"Spatial Graph View 2" nodeScaleFactor setMinMax 0 1
"Spatial Graph View 2" nodeScaleFactor setButtons 0
"Spatial Graph View 2" nodeScaleFactor setEditButton 1
"Spatial Graph View 2" nodeScaleFactor setIncrement 0.0666667
"Spatial Graph View 2" nodeScaleFactor setValue 0.1
"Spatial Graph View 2" nodeScaleFactor setSubMinMax 0 119.735794067383
"Spatial Graph View 2" nodeColoring setIndex 0 0
"Spatial Graph View 2" nodeLabelColoringOptions setValue 0
"Spatial Graph View 2" nodeColor setColor 0 0.8 0.8 0.8
"Spatial Graph View 2" segmentOnOff setValue 1
"Spatial Graph View 2" segmentStyle setValue 0 0
"Spatial Graph View 2" segmentStyle setToggleVisible 0 1
"Spatial Graph View 2" segmentStyle setValue 1 0
"Spatial Graph View 2" segmentStyle setToggleVisible 1 1
"Spatial Graph View 2" segmentStyle setValue 2 1
"Spatial Graph View 2" segmentStyle setToggleVisible 2 1
"Spatial Graph View 2" tubeScale setIndex 0 0
"Spatial Graph View 2" fire
"Spatial Graph View 2" tubeScaleFactor setMinMax 0 1
"Spatial Graph View 2" tubeScaleFactor setButtons 0
"Spatial Graph View 2" tubeScaleFactor setEditButton 1
"Spatial Graph View 2" tubeScaleFactor setIncrement 0.0666667
"Spatial Graph View 2" tubeScaleFactor setValue 0.1
"Spatial Graph View 2" tubeScaleFactor setSubMinMax 0 7.89647245407104
"Spatial Graph View 2" segmentWidth setMinMax 0 10
"Spatial Graph View 2" segmentWidth setButtons 0
"Spatial Graph View 2" segmentWidth setEditButton 1
"Spatial Graph View 2" segmentWidth setIncrement 0.666667
"Spatial Graph View 2" segmentWidth setValue 1
"Spatial Graph View 2" segmentWidth setSubMinMax 0 10
"Spatial Graph View 2" segmentColoring setIndex 0 0
"Spatial Graph View 2" segmentLabelColoringOptions setValue 0
"Spatial Graph View 2" segmentColor setColor 0 0 0 0
"Spatial Graph View 2" pointSize setMinMax 0 15
"Spatial Graph View 2" pointSize setButtons 0
"Spatial Graph View 2" pointSize setEditButton 1
"Spatial Graph View 2" pointSize setIncrement 1
"Spatial Graph View 2" pointSize setValue 4
"Spatial Graph View 2" pointSize setSubMinMax 0 15
"Spatial Graph View 2" setVisibility HIJMPLPPBPBFAAAAIHIIAPPB HIJMPLPPBPBFAAAAIHIIAPPB
"Spatial Graph View 2" fire
"Spatial Graph View 2" setViewerMask 16383
"Spatial Graph View 2" setPickable 1

set hideNewModules 0
create HxDisplayLandmarks "VPMcolor"
"VPMcolor" setIconPosition 339 874
"VPMcolor" setVar "CustomHelp" {HxDisplayLandmarks}
"VPMcolor" setVar "CustomXML" {HxDisplayLandmarks_config.xml}
"VPMcolor" setColor 0 0 0 0
"VPMcolor" setColor 1 0.4 0.63 0.7
"VPMcolor" setColor 2 0.4 0.75 0.11
"VPMcolor" data connect "VPM.landmarkAscii"
"VPMcolor" fire
"VPMcolor" chooseSet setIndex 0 0
"VPMcolor" display setValue 0 0
"VPMcolor" display setToggleVisible 0 1
"VPMcolor" drawStyle setValue 0 0
"VPMcolor" drawStyle setToggleVisible 0 1
"VPMcolor" drawStyle setValue 1 0
"VPMcolor" drawStyle setToggleVisible 1 1
"VPMcolor" size setMinMax 0 5
"VPMcolor" size setButtons 0
"VPMcolor" size setEditButton 1
"VPMcolor" size setIncrement 0.333333
"VPMcolor" size setValue 0.6
"VPMcolor" size setSubMinMax 0 5
"VPMcolor" complexity setMinMax 0 1
"VPMcolor" complexity setButtons 0
"VPMcolor" complexity setEditButton 1
"VPMcolor" complexity setIncrement 0.1
"VPMcolor" complexity setValue 0.25
"VPMcolor" complexity setSubMinMax 0 1
"VPMcolor" setBaseSize 127.248
"VPMcolor" fire
"VPMcolor" setViewerMask 16383
"VPMcolor" setPickable 1

set hideNewModules 0

viewer 0 setCameraOrientation -0.364165 -0.703848 -0.609903 3.66377
viewer 0 setCameraPosition 487.931 837.164 -34.2158
viewer 0 setCameraFocalDistance 687.774
viewer 0 setCameraNearDistance 164.269
viewer 0 setCameraFarDistance 1013.5
viewer 0 setCameraType orthographic
viewer 0 setCameraHeight 558.647
viewer 0 setAutoRedraw 1
viewer 0 redraw

correlationPanel closeTabs
correlationPanel setTabName 0 "Correlation 1"
correlationPanel 0 setLogScalingOnAxis 0 0
correlationPanel 0 setLogScalingOnAxis 1 0

histogramPanel closeTabs
histogramPanel setTabName 0 "Histogram 1"
histogramPanel 0 setLogScalingOnAxis 0 0
histogramPanel 0 setLogScalingOnAxis 1 1

